Repository softeer5th/Team4-enDolphin, pull requests merged in 2025-01, with the labels that each got.

#9 [Feat] Vite 초기 세팅
  frontend/.gitignore
  frontend/README.md
  frontend/eslint.config.js
  frontend/index.html
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/public/vite.svg
  frontend/src/App.tsx
  frontend/src/apis/index.ts
  frontend/src/components/Button/index.tsx
  frontend/src/main.tsx
  frontend/src/pages/index.tsx
  frontend/src/theme/index.ts
  frontend/src/utils/index.ts
  frontend/src/vite-env.d.ts
  frontend/tsconfig.app.json
  frontend/tsconfig.json
  frontend/tsconfig.node.json
  frontend/vite.config.ts
Labels: FE

#10 [BE-Feature] 백엔드 프로젝트 초기 세팅
  backend/.gitattributes
  backend/.gitignore
  backend/build.gradle
  backend/gradle/wrapper/gradle-wrapper.jar
  backend/gradle/wrapper/gradle-wrapper.properties
  backend/gradlew
  backend/gradlew.bat
  backend/settings.gradle
  backend/src/main/java/endolphin/backend/BackendApplication.java
  backend/src/main/resources/application.properties
  backend/src/test/java/endolphin/backend/BackendApplicationTests.java
Labels: BE

#15 [FE-Feat] Vanilla Extract 초기 설정 및 디자인 토큰 주입
  frontend/.gitignore
  frontend/.vscode/settings.json
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/public/fonts/Pretendard-Light.woff2
  frontend/public/fonts/Pretendard-Medium.woff2
  frontend/public/fonts/Pretendard-Regular.woff2
  frontend/public/fonts/Pretendard-SemiBold.woff2
  frontend/src/App.tsx
  frontend/src/components/Text/index.tsx
  frontend/src/components/Text/text.css.ts
  frontend/src/scripts/create-theme.cjs
  frontend/src/theme/color.ts
  frontend/src/theme/font.ts
  frontend/src/theme/gradient.ts
  frontend/src/theme/index.css.ts
  frontend/src/theme/index.ts
  frontend/src/theme/radius.ts
  frontend/src/theme/spacing.ts
  frontend/src/theme/tokens/tokens.json
  frontend/src/theme/typo.ts
  frontend/vite.config.ts
Labels: FE

#13 [BE-Feat] Spring Profile 설정
  backend/.gitignore
  backend/src/main/resources/application.properties
  backend/src/main/resources/application.yml
Labels: BE

#27 [BE-Feat] security 기능 구현
  backend/src/main/java/endolphin/backend/global/security/JwtAuthFilter.java
  backend/src/main/java/endolphin/backend/global/security/JwtProvider.java
  backend/src/main/java/endolphin/backend/global/security/SecurityConfig.java
  backend/src/main/java/endolphin/backend/global/security/UserContext.java
  backend/src/main/java/endolphin/backend/global/security/UserInfo.java
  backend/src/test/java/endolphin/backend/global/security/JwtAuthFilterTest.java
  backend/src/test/java/endolphin/backend/global/security/JwtProviderTest.java
Labels: 🛠️ BE

#28 [FE-Feat] Dropdown 컴포넌트 구현
  frontend/src/components/Dropdown/Dropdown.stories.tsx
  frontend/src/components/Dropdown/DropdownContext.ts
  frontend/src/components/Dropdown/DropdownItem.tsx
  frontend/src/components/Dropdown/dropdownItem.css.ts
  frontend/src/components/Dropdown/index.css.ts
  frontend/src/components/Dropdown/index.tsx
  frontend/src/hooks/useSafeContext.ts
Labels: 🖥️ FE

#32 [BE-Feat] 구글 로그인 및 회원가입 구현
  .github/pull_request_template.md
  backend/src/main/java/endolphin/backend/BackendApplication.java
  backend/src/main/java/endolphin/backend/domain/user/UserController.java
  backend/src/main/java/endolphin/backend/domain/user/UserRepository.java
  backend/src/main/java/endolphin/backend/domain/user/UserService.java
  backend/src/main/java/endolphin/backend/domain/user/dto/GoogleTokens.java
  backend/src/main/java/endolphin/backend/domain/user/dto/GoogleUserInfo.java
  backend/src/main/java/endolphin/backend/domain/user/dto/OAuthResponse.java
  backend/src/main/java/endolphin/backend/domain/user/dto/UrlResponse.java
  backend/src/main/java/endolphin/backend/domain/user/entity/User.java
  backend/src/main/java/endolphin/backend/global/config/GoogleOAuthProperties.java
  backend/src/main/java/endolphin/backend/global/config/RestTemplateConfig.java
  backend/src/main/java/endolphin/backend/global/security/JwtAuthFilter.java
  backend/src/test/java/endolphin/backend/domain/user/UserServiceTest.java
Labels: 🛠️ BE

#19 [ALL-Feat] git hook 설정
  .github/hooks/commit-msg
  .github/hooks/pre-commit
  .github/hooks/pre-push
  .gitignore
  frontend/.vscode/settings.json
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/src/scripts/git-hook-init-command.sh
  frontend/src/theme/index.ts
Labels: 🔮 ALL

#33 [BE-Refactor] 로그인 기능 리팩토링
  backend/src/main/java/endolphin/backend/domain/user/UserController.java
  backend/src/main/java/endolphin/backend/domain/user/UserService.java
  backend/src/main/java/endolphin/backend/domain/user/dto/GoogleTokens.java
  backend/src/main/java/endolphin/backend/domain/user/dto/GoogleUserInfo.java
  backend/src/main/java/endolphin/backend/global/security/JwtAuthFilter.java
  backend/src/test/java/endolphin/backend/domain/user/UserServiceTest.java
Labels: 🛠️ BE
