Repository softeer5th/Team4-enDolphin, pull requests merged in 2025-02, with the labels that each got.

#35 [BE-Feat] JPA Entity 작성
  backend/src/main/java/endolphin/backend/domain/discussion/DiscussionParticipantRepository.java
  backend/src/main/java/endolphin/backend/domain/discussion/DiscussionRepository.java
  backend/src/main/java/endolphin/backend/domain/discussion/entity/Discussion.java
  backend/src/main/java/endolphin/backend/domain/discussion/entity/DiscussionParticipant.java
  backend/src/main/java/endolphin/backend/domain/discussion/enums/Role.java
  backend/src/main/java/endolphin/backend/domain/personal_event/PersonalEventRepository.java
  backend/src/main/java/endolphin/backend/domain/personal_event/entity/PersonalEvent.java
  backend/src/main/java/endolphin/backend/domain/shared_event/SharedEventRepository.java
  backend/src/main/java/endolphin/backend/domain/shared_event/entity/SharedEvent.java
  backend/src/main/java/endolphin/backend/domain/user/entity/User.java
  backend/src/main/java/endolphin/backend/global/base_entity/BaseTimeEntity.java
  backend/src/main/java/endolphin/backend/global/config/JpaAuditingConfig.java
Labels: 🛠️ BE

#38 [BE-Feat] git hook 백엔드 스크립트 추가
  .github/hooks/pre-commit
  .github/hooks/pre-push
  backend/build.gradle
Labels: 🛠️ BE

#40 [All-Feat] github action을 이용하여 slack 연동
  .github/workflows/slack-notification.yml
Labels: 🔮 ALL

#41 [BE-Fix] 구글 로그인 callback 버그 수정
  backend/src/main/java/endolphin/backend/domain/user/UserController.java
  backend/src/main/java/endolphin/backend/global/security/JwtAuthFilter.java
Labels: 🛠️ BE

#37 [FE-Feat] Button Component 구현
  frontend/src/components/Button/Button.stories.tsx
  frontend/src/components/Button/ButtonIcon.tsx
  frontend/src/components/Button/ButtonText.tsx
  frontend/src/components/Button/buttonIcon.css.ts
  frontend/src/components/Button/index.css.ts
  frontend/src/components/Button/index.tsx
  frontend/src/components/Dropdown/DropdownItem.tsx
  frontend/src/components/Icon/index.ts
Labels: 🖥️ FE

#50 [FE-Feat] Pagination 컴포넌트 작성
  frontend/src/components/Icon/component/IconDotsMono.tsx
  frontend/src/components/Icon/index.ts
  frontend/src/components/Icon/svg/icon-dots-mono.svg
  frontend/src/components/Pagination/Pagination.stories.tsx
  frontend/src/components/Pagination/PaginationItem.tsx
  frontend/src/components/Pagination/index.css.ts
  frontend/src/components/Pagination/index.tsx
Labels: 🖥️ FE

#48 [FE-Feat] Tooltip 컴포넌트 작성
  frontend/src/components/Tooltip/TooltipArrow/TooltipArrowDown.tsx
  frontend/src/components/Tooltip/TooltipArrow/TooltipArrowLeft.tsx
  frontend/src/components/Tooltip/TooltipArrow/TooltipArrowRight.tsx
  frontend/src/components/Tooltip/TooltipArrow/TooltipArrowUp.tsx
  frontend/src/components/Tooltip/TooltipArrow/index.ts
  frontend/src/components/Tooltip/TooltipContent.tsx
  frontend/src/components/Tooltip/index.css.ts
  frontend/src/components/Tooltip/index.tsx
  frontend/src/components/Tooltip/tooltip.stories.tsx
  frontend/src/components/Tooltip/tooltipContent.css.ts
Labels: 🖥️ FE

#55 [ALL-Feat] PR open 시 리뷰 요청 알림의 중복 전송을 방지 #47
  .github/workflows/slack-notification.yml
Labels: 🔮 ALL

#52 [FE-Feat] Segment Control 컴포넌트 구현
  frontend/src/components/SegmentControl/SegmentControl.stories.tsx
  frontend/src/components/SegmentControl/index.css.ts
  frontend/src/components/SegmentControl/index.tsx
Labels: 🖥️ FE

#81 [FE-Chore] JSX를 위한 eslint 규칙 추가
  frontend/eslint.config.js
  frontend/src/components/Button/ButtonIcon.tsx
  frontend/src/components/Checkbox/CheckboxLabel.tsx
  frontend/src/components/Checkbox/index.tsx
  frontend/src/components/Chip/index.tsx
  frontend/src/components/Dropdown/Dropdown.stories.tsx
  frontend/src/components/Dropdown/index.tsx
  frontend/src/components/Group/index.tsx
  frontend/src/components/Icon/component/TooltipArrow/TooltipArrowDown.tsx
  frontend/src/components/Icon/component/TooltipArrow/TooltipArrowLeft.tsx
  frontend/src/components/Icon/component/TooltipArrow/TooltipArrowRight.tsx
  frontend/src/components/Icon/component/TooltipArrow/TooltipArrowUp.tsx
  frontend/src/components/Icon/component/TooltipArrow/index.ts
  frontend/src/components/Icon/index.ts
  frontend/src/components/Notification/GlobalNotification.tsx
  frontend/src/components/Notification/NotificationProvider.tsx
  frontend/src/components/Notification/index.tsx
  frontend/src/components/Pagination/index.tsx
  frontend/src/components/Tab/TabContent.tsx
  frontend/src/components/Tab/index.tsx
  frontend/src/components/Text/index.tsx
  frontend/src/components/Tooltip/index.tsx
Labels: 🖥️ FE

#45 [BE-Feat] 개인일정 CRUD 기능 구현
  backend/src/main/java/endolphin/backend/domain/personal_event/PersonalEventController.java
  backend/src/main/java/endolphin/backend/domain/personal_event/PersonalEventRepository.java
  backend/src/main/java/endolphin/backend/domain/personal_event/PersonalEventService.java
  backend/src/main/java/endolphin/backend/domain/personal_event/dto/PersonalEventRequest.java
  backend/src/main/java/endolphin/backend/domain/personal_event/dto/PersonalEventResponse.java
  backend/src/main/java/endolphin/backend/domain/personal_event/entity/PersonalEvent.java
  backend/src/main/java/endolphin/backend/domain/user/UserService.java
  backend/src/main/java/endolphin/backend/global/dto/ListResponse.java
  backend/src/main/java/endolphin/backend/global/util/Validator.java
  backend/src/test/java/endolphin/backend/domain/personal_event/PersonalEventControllerTest.java
  backend/src/test/java/endolphin/backend/domain/personal_event/PersonalEventRepositoryTest.java
  backend/src/test/java/endolphin/backend/domain/personal_event/PersonalEventServiceTest.java
  backend/src/test/java/endolphin/backend/global/util/ValidatorTest.java
Labels: 🛠️ BE

#80 [FE-Feat] 내 일정 관리 페이지 캘린더 구현
  frontend/eslint.config.js
  frontend/src/components/Calendar/Calendar.stories.ts
  frontend/src/components/Calendar/Core/SelectedWeek.tsx
  frontend/src/components/Calendar/Core/TimeControl.tsx
  frontend/src/components/Calendar/Core/TimeControlButton.tsx
  frontend/src/components/Calendar/Core/WeekCell.tsx
  frontend/src/components/Calendar/Core/index.css.ts
  frontend/src/components/Calendar/Core/index.tsx
  frontend/src/components/Calendar/Header/CalendarHeader.tsx
  frontend/src/components/Calendar/Header/index.css.ts
  frontend/src/components/Calendar/Table/CalendarCell.tsx
  frontend/src/components/Calendar/Table/CalendarDay.tsx
  frontend/src/components/Calendar/Table/CalendarSide.tsx
  frontend/src/components/Calendar/Table/SideCell.tsx
  frontend/src/components/Calendar/Table/index.css.ts
  frontend/src/components/Calendar/Table/index.tsx
  frontend/src/components/Calendar/context/CalendarContext.ts
  frontend/src/components/Calendar/context/CalendarProvider.tsx
  frontend/src/components/Calendar/index.css.ts
  frontend/src/components/Calendar/index.tsx
  frontend/src/components/Icon/component/ChevronLeft.tsx
  frontend/src/components/Icon/component/ChevronRight.tsx
  frontend/src/components/Icon/index.ts
  frontend/src/components/Icon/svg/chevron-left.svg
  frontend/src/components/Icon/svg/chevron-right.svg
  frontend/src/constants/date.ts
  frontend/src/hooks/useCalendar.ts
  frontend/src/utils/clsx/index.ts
  frontend/src/utils/date/date.test.ts
  frontend/src/utils/date/index.ts
Labels: 🖥️ FE

#54 [All-Fix] git hook의 로컬 검증 코드 실행 기준을 변경
  .github/hooks/pre-commit
  .github/hooks/pre-push
Labels: 🔮 ALL

#53 [FE-Feat] Input 컴포넌트 작성
  frontend/pnpm-lock.yaml
  frontend/src/components/Icon/component/ChevronDown.tsx
  frontend/src/components/Icon/index.ts
  frontend/src/components/Icon/svg/chevron-down.svg
  frontend/src/components/Input/HelperText.tsx
  frontend/src/components/Input/Input.stories.tsx
  frontend/src/components/Input/InputContext.ts
  frontend/src/components/Input/InputField.tsx
  frontend/src/components/Input/Label.tsx
  frontend/src/components/Input/MultiInput.tsx
  frontend/src/components/Input/SingleInput.tsx
  frontend/src/components/Input/helperText.css.ts
  frontend/src/components/Input/index.css.ts
  frontend/src/components/Input/index.tsx
  frontend/src/components/Input/inputField.css.ts
  frontend/src/components/Input/label.css.ts
Labels: 🖥️ FE

#84 [FE-Feat] Flex 컴포넌트 구현
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/src/components/Calendar/Core/TimeControl.tsx
  frontend/src/components/Flex/Flex.stories.tsx
  frontend/src/components/Flex/flex.css.ts
  frontend/src/components/Flex/index.tsx
Labels: 🖥️ FE

#89 [FE-Feat] Tanstack Router 설정, 스토리북 폴더 정리
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/src/App.tsx
  frontend/src/components/Calendar/Calendar.stories.ts
  frontend/src/components/Checkbox/Checkbox.stories.tsx
  frontend/src/components/Chip/Chip.stories.ts
  frontend/src/components/Dropdown/Dropdown.stories.tsx
  frontend/src/components/Notification/Notification.stories.tsx
  frontend/src/components/Tab/Tab.stories.tsx
  frontend/src/components/Tooltip/tooltip.stories.tsx
  frontend/src/envconfig.ts
  frontend/src/main.tsx
  frontend/src/pages/Home/index.tsx
  frontend/src/pages/index.tsx
  frontend/src/routeTree.gen.ts
  frontend/src/routes/__root.tsx
  frontend/src/routes/index.lazy.tsx
  frontend/src/routes/my-schedule/@components/index.tsx
  frontend/src/routes/my-schedule/index.lazy.tsx
  frontend/tsconfig.app.json
  frontend/vite.config.ts
Labels: 🖥️ FE

#87 [BE-Feat] Spring Swagger 사용 설정
  backend/build.gradle
  backend/src/main/java/endolphin/backend/global/config/SwaggerConfig.java
  backend/src/main/java/endolphin/backend/global/security/JwtAuthFilter.java
Labels: 🛠️ BE

#79 [BE-Feat] Api 공통 에러 처리 기능 구현
  backend/src/main/java/endolphin/backend/global/error/ErrorResponse.java
  backend/src/main/java/endolphin/backend/global/error/GlobalExceptionHandler.java
  backend/src/main/java/endolphin/backend/global/error/exception/ApiException.java
  backend/src/main/java/endolphin/backend/global/error/exception/ErrorCode.java
Labels: 🛠️ BE

#90 [FE-Feat] 캘린더 카드 컴포넌트 마크업 및 아이콘 생성 로직 수정
  frontend/src/components/Calendar/Core/TimeControl.tsx
  frontend/src/components/Chip/Chip.stories.ts
  frontend/src/components/Chip/index.css.ts
  frontend/src/components/Chip/index.tsx
  frontend/src/components/Flex/Flex.stories.tsx
  frontend/src/components/Flex/index.tsx
  frontend/src/components/Icon/Icon.d.ts
  frontend/src/components/Icon/component/Check.tsx
  frontend/src/components/Icon/component/ChevronDown.tsx
  frontend/src/components/Icon/component/ChevronLeft.tsx
  frontend/src/components/Icon/component/ChevronRight.tsx
  frontend/src/components/Icon/component/CircleCheck.tsx
  frontend/src/components/Icon/component/GoogleCalendar.tsx
  frontend/src/components/Icon/component/IconDotsMono.tsx
  frontend/src/components/Icon/component/Pencil.tsx
  frontend/src/components/Icon/component/TriangleWarning.tsx
  frontend/src/components/Icon/index.ts
  frontend/src/components/Icon/svg/google-calendar.svg
  frontend/src/components/Icon/svg/pencil.svg
  frontend/src/constants/statusMap.ts
  frontend/src/routes/my-schedule/@components/CalendarCard/CardBottom.tsx
  frontend/src/routes/my-schedule/@components/CalendarCard/index.css.ts
  frontend/src/routes/my-schedule/@components/CalendarCard/index.tsx
  frontend/src/routes/my-schedule/@components/index.tsx
  frontend/src/routes/my-schedule/index.lazy.tsx
  frontend/src/scripts/create-icon.cjs
  frontend/src/utils/date/date.ts
  frontend/src/utils/date/index.ts
  frontend/src/utils/date/time.ts
Labels: 🖥️ FE

#83 [BE-Feat]논의 생성 기능 구현
  backend/src/main/java/endolphin/backend/domain/discussion/DiscussionController.java
  backend/src/main/java/endolphin/backend/domain/discussion/DiscussionService.java
  backend/src/main/java/endolphin/backend/domain/discussion/dto/CreateDiscussionRequest.java
  backend/src/main/java/endolphin/backend/domain/discussion/dto/CreateDiscussionResponse.java
  backend/src/main/java/endolphin/backend/domain/discussion/entity/Discussion.java
  backend/src/main/java/endolphin/backend/domain/discussion/entity/DiscussionParticipant.java
  backend/src/main/java/endolphin/backend/domain/discussion/enums/DiscussionStatus.java
  backend/src/main/java/endolphin/backend/domain/discussion/enums/MeetingMethod.java
  backend/src/main/java/endolphin/backend/domain/personal_event/PersonalEventController.java
  backend/src/main/java/endolphin/backend/global/util/URIUtil.java
  backend/src/main/java/endolphin/backend/global/util/Validator.java
  backend/src/test/java/endolphin/backend/domain/discussion/DiscussionControllerTest.java
  backend/src/test/java/endolphin/backend/domain/discussion/DiscussionServiceTest.java
Labels: 🛠️ BE

#91 [All-Feat] 코드오너 설정 및 Auto Assign
  .github/CODEOWNERS
  .github/hooks/pre-push
  .github/workflows/auto-assign.yml
Labels: 🔮 ALL

#95 [FE-Feat] 캘린더 드래그 또는 클릭으로 시간 선택 구현
  frontend/src/components/Calendar/Core/SelectedWeek.tsx
  frontend/src/components/Calendar/Core/TimeControlButton.tsx
  frontend/src/components/Calendar/Core/WeekCell.tsx
  frontend/src/components/Calendar/Core/index.css.ts
  frontend/src/components/Calendar/Header/CalendarHeader.tsx
  frontend/src/components/Calendar/Table/CalendarCell.tsx
  frontend/src/components/Calendar/Table/CalendarDay.tsx
  frontend/src/components/Calendar/Table/CalendarDetailCell.tsx
  frontend/src/components/Calendar/Table/index.css.ts
  frontend/src/components/Calendar/Table/index.tsx
  frontend/src/components/Calendar/context/TimeTableContext.ts
  frontend/src/components/Calendar/context/TimeTableProvider.tsx
  frontend/src/components/Calendar/index.tsx
  frontend/src/components/Notification/GlobalNotification.tsx
  frontend/src/constants/date.ts
  frontend/src/hooks/useClickOutside.ts
  frontend/src/hooks/useSelectTime.ts
  frontend/src/theme/animation.css.ts
  frontend/src/utils/date/date.ts
Labels: 🖥️ FE

#92 [BE-Feat] 백엔드 api 도커 컨테이너 실행 스크립트 구현
  .gitignore
  backend/Dockerfile.dev
  script/docker-compose-dev.yml
  script/setup_and_run.sh
  script/wait-for-it.sh
Labels: 🛠️ BE

#100 [FE-Feat] Input 컴포넌트의 border 적용 위치를 동적으로 선택 가능하도록 구현
  frontend/src/components/Input/Core/HelperText.tsx
  frontend/src/components/Input/Core/InputField.tsx
  frontend/src/components/Input/Core/Label.tsx
  frontend/src/components/Input/Core/helperText.css.ts
  frontend/src/components/Input/Core/inputField.css.ts
  frontend/src/components/Input/Core/label.css.ts
  frontend/src/components/Input/Input.stories.tsx
  frontend/src/components/Input/InputContext.ts
  frontend/src/components/Input/MultiInput.tsx
  frontend/src/components/Input/SingleInput.tsx
  frontend/src/components/Input/index.css.ts
  frontend/src/utils/jsxUtils.tsx
Labels: 🖥️ FE

#94 [BE-Feat] swagger 관련 어노테이션 추가
  backend/build.gradle
  backend/src/main/java/endolphin/backend/domain/discussion/DiscussionController.java
  backend/src/main/java/endolphin/backend/domain/personal_event/PersonalEventController.java
  backend/src/main/java/endolphin/backend/domain/user/UserController.java
  backend/src/main/java/endolphin/backend/domain/user/UserService.java
  backend/src/main/java/endolphin/backend/domain/user/entity/User.java
  backend/src/main/java/endolphin/backend/global/error/ErrorResponse.java
  backend/src/main/java/endolphin/backend/global/error/GlobalExceptionHandler.java
  backend/src/main/java/endolphin/backend/global/error/exception/ErrorCode.java
  backend/src/main/java/endolphin/backend/global/util/Validator.java
  backend/src/test/java/endolphin/backend/domain/user/UserServiceTest.java
  backend/src/test/java/endolphin/backend/global/util/ValidatorTest.java
Labels: 🛠️ BE

#97 [BE-Feat] 로그 세팅 추가
  backend/src/main/java/endolphin/backend/global/config/FilterConfig.java
  backend/src/main/java/endolphin/backend/global/logging/LogFilter.java
  backend/src/main/java/endolphin/backend/global/security/SecurityConfig.java
  backend/src/main/resources/logback-spring.xml
Labels: 🛠️ BE

#101 [FE-Feat] 일정 추가, 수정 팝오버 컴포넌트 구현
  frontend/src/components/Button/index.tsx
  frontend/src/components/Icon/component/Plus.tsx
  frontend/src/components/Icon/index.ts
  frontend/src/components/Icon/svg/plus.svg
  frontend/src/components/Input/Core/HelperText.tsx
  frontend/src/components/Input/MultiInput.tsx
  frontend/src/components/Input/SingleInput.tsx
  frontend/src/components/Text/index.tsx
  frontend/src/components/Toggle/Toggle.stories.tsx
  frontend/src/components/Toggle/index.css.ts
  frontend/src/components/Toggle/index.tsx
  frontend/src/routes/my-schedule/@components/SchedulePopover/PopoverButton.tsx
  frontend/src/routes/my-schedule/@components/SchedulePopover/PopoverForm.tsx
  frontend/src/routes/my-schedule/@components/SchedulePopover/Title.tsx
  frontend/src/routes/my-schedule/@components/SchedulePopover/index.css.ts
  frontend/src/routes/my-schedule/@components/SchedulePopover/index.tsx
  frontend/src/routes/my-schedule/@components/index.tsx
  frontend/src/routes/my-schedule/@types/index.ts
  frontend/src/theme/reset.css.ts
Labels: 🖥️ FE

#107 [FE-Feat] Avatar 컴포넌트 기본 레이아웃 작성
  frontend/src/components/Avatar/Avatar.stories.tsx
  frontend/src/components/Avatar/AvatarCount.tsx
  frontend/src/components/Avatar/AvatarItem.tsx
  frontend/src/components/Avatar/index.css.ts
  frontend/src/components/Avatar/index.tsx
Labels: 🖥️ FE

#98 [BE-Feat] Redis 사용 세팅
  backend/build.gradle
  backend/src/main/java/endolphin/backend/global/config/RedisConfig.java
  backend/src/main/java/endolphin/backend/global/redis/DiscussionBitmapService.java
  backend/src/test/java/endolphin/backend/global/redis/DiscussionBitmapServiceTest.java
  backend/src/test/java/endolphin/backend/global/redis/RedisTemplateTest.java
  backend/src/test/java/endolphin/backend/global/redis/RedisTestContainer.java
Labels: 🛠️ BE

#118 [BE-Fix] 도커 컨테이너 실행 버그 수정
  backend/Dockerfile.dev
  backend/src/test/java/endolphin/backend/global/redis/RedisTestContainer.java
  backend/src/test/resources/application.yml
  script/docker-compose-dev.yml
  script/setup_and_run.sh
Labels: 🛠️ BE

#117 [FE-Feat] Main Layout, Global Header 구현
  frontend/src/components/Icon/component/ArrowLeft.tsx
  frontend/src/components/Icon/component/Logo.tsx
  frontend/src/components/Icon/index.ts
  frontend/src/components/Icon/svg/logo.svg
  frontend/src/features/my-schedule/model/index.ts
  frontend/src/features/my-schedule/ui/CalendarCard/CardBottom.tsx
  frontend/src/features/my-schedule/ui/CalendarCard/index.css.ts
  frontend/src/features/my-schedule/ui/CalendarCard/index.tsx
  frontend/src/features/my-schedule/ui/SchedulePopover/PopoverButton.tsx
  frontend/src/features/my-schedule/ui/SchedulePopover/PopoverForm.tsx
  frontend/src/features/my-schedule/ui/SchedulePopover/Title.tsx
  frontend/src/features/my-schedule/ui/SchedulePopover/index.css.ts
  frontend/src/features/my-schedule/ui/SchedulePopover/index.tsx
  frontend/src/layout/GlobalNavBar/buttons/LoginLink.tsx
  frontend/src/layout/GlobalNavBar/buttons/MyScheduleLink.tsx
  frontend/src/layout/GlobalNavBar/buttons/NewDiscussionLink.tsx
  frontend/src/layout/GlobalNavBar/buttons/index.ts
  frontend/src/layout/GlobalNavBar/index.css.ts
  frontend/src/layout/GlobalNavBar/index.tsx
  frontend/src/layout/MainLayout/index.css.ts
  frontend/src/layout/MainLayout/index.tsx
  frontend/src/pages/ErrorPage/index.tsx
  frontend/src/pages/LandingPage/index.css.ts
  frontend/src/pages/LandingPage/index.tsx
  frontend/src/pages/MySchedulePage/index.tsx
  frontend/src/routeTree.gen.ts
  frontend/src/routes/__root.tsx
  frontend/src/routes/_main.tsx
  frontend/src/routes/_main/my-schedule/index.lazy.tsx
  frontend/src/routes/landing/@components/LandingImages.tsx
  frontend/src/routes/landing/@components/index.tsx
  frontend/src/routes/landing/index.tsx
  frontend/src/routes/my-schedule/@components/index.tsx
  frontend/src/routes/my-schedule/index.lazy.tsx
Labels: 🖥️ FE

#116 [FE-Feat] 일정 조율 생성 완료 페이지 구현
  frontend/public/images/assets/calendar.webp
  frontend/src/components/Button/index.tsx
  frontend/src/components/Divider/Divider.stories.tsx
  frontend/src/components/Divider/index.css.ts
  frontend/src/components/Divider/index.tsx
  frontend/src/components/Dropdown/DropdownContext.ts
  frontend/src/components/Dropdown/DropdownItem.tsx
  frontend/src/components/Dropdown/index.css.ts
  frontend/src/components/Dropdown/index.tsx
  frontend/src/components/Flex/Flex.stories.tsx
  frontend/src/components/Flex/index.tsx
  frontend/src/hooks/useClipboard.ts
  frontend/src/routeTree.gen.ts
  frontend/src/routes/__root.tsx
  frontend/src/routes/discussion/@components/DiscussionCreateCard/DiscussionInfo.tsx
  frontend/src/routes/discussion/@components/DiscussionCreateCard/index.css.ts
  frontend/src/routes/discussion/@components/DiscussionCreateCard/index.tsx
  frontend/src/routes/discussion/@components/index.css.ts
  frontend/src/routes/discussion/@components/index.tsx
  frontend/src/routes/discussion/create/$id.tsx
  frontend/src/types/polymorphism.ts
Labels: 🖥️ FE

#112 [BE-Feat] 구글 토큰 관리 기능 구현
  backend/src/main/java/endolphin/backend/domain/auth/AuthController.java
  backend/src/main/java/endolphin/backend/domain/auth/AuthService.java
  backend/src/main/java/endolphin/backend/domain/auth/dto/OAuthResponse.java
  backend/src/main/java/endolphin/backend/domain/auth/dto/UrlResponse.java
  backend/src/main/java/endolphin/backend/domain/user/UserController.java
  backend/src/main/java/endolphin/backend/domain/user/UserService.java
  backend/src/main/java/endolphin/backend/domain/user/entity/User.java
  backend/src/main/java/endolphin/backend/global/config/RestClientConfig.java
  backend/src/main/java/endolphin/backend/global/error/GlobalExceptionHandler.java
  backend/src/main/java/endolphin/backend/global/error/exception/ErrorCode.java
  backend/src/main/java/endolphin/backend/global/error/exception/OAuthException.java
  backend/src/main/java/endolphin/backend/global/google/GoogleOAuthService.java
  backend/src/main/java/endolphin/backend/global/google/dto/GoogleTokens.java
  backend/src/main/java/endolphin/backend/global/google/dto/GoogleUserInfo.java
  backend/src/test/java/endolphin/backend/domain/auth/AuthServiceTest.java
Labels: 🛠️ BE

#131 [FE-Feat] 모달 컴포넌트, 글로벌 모달 컴포넌트 구현
  frontend/src/components/Modal/GlobalModal.tsx
  frontend/src/components/Modal/Modal.stories.tsx
  frontend/src/components/Modal/ModalContents.tsx
  frontend/src/components/Modal/ModalContext.ts
  frontend/src/components/Modal/ModalFooter.tsx
  frontend/src/components/Modal/ModalProvider.tsx
  frontend/src/components/Modal/index.css.ts
  frontend/src/components/Modal/index.tsx
  frontend/src/features/discussion/ui/DiscussionCreateCard/DiscussionInfo.tsx
  frontend/src/features/discussion/ui/DiscussionCreateCard/index.css.ts
  frontend/src/features/discussion/ui/DiscussionCreateCard/index.tsx
  frontend/src/hooks/useModal.ts
  frontend/src/pages/DiscussionCreateFinishPage/index.css.ts
  frontend/src/pages/DiscussionCreateFinishPage/index.tsx
  frontend/src/routes/discussion/create/$id.tsx
Labels: 🖥️ FE

#119 [BE-Feat] 논의 확정 이후 비즈니스 로직 구현
  backend/src/main/java/endolphin/backend/domain/discussion/DiscussionController.java
  backend/src/main/java/endolphin/backend/domain/discussion/DiscussionParticipantRepository.java
  backend/src/main/java/endolphin/backend/domain/discussion/DiscussionParticipantService.java
  backend/src/main/java/endolphin/backend/domain/discussion/DiscussionService.java
  backend/src/main/java/endolphin/backend/domain/personal_event/PersonalEventService.java
  backend/src/main/java/endolphin/backend/domain/shared_event/SharedEventService.java
  backend/src/main/java/endolphin/backend/domain/shared_event/dto/SharedEventDto.java
  backend/src/main/java/endolphin/backend/domain/shared_event/dto/SharedEventRequest.java
  backend/src/main/java/endolphin/backend/domain/shared_event/dto/SharedEventWithDiscussionInfoResponse.java
  backend/src/main/java/endolphin/backend/global/config/EnableAsyncConfig.java
  backend/src/main/java/endolphin/backend/global/error/exception/ApiException.java
  backend/src/main/java/endolphin/backend/global/redis/DiscussionBitmapService.java
  backend/src/test/java/endolphin/backend/domain/discussion/DiscussionServiceTest.java
  backend/src/test/java/endolphin/backend/domain/shared_event/SharedEventServiceTest.java
  backend/src/test/java/endolphin/backend/global/redis/DiscussionBitmapServiceTest.java
Labels: 🛠️ BE

#133 [FE-Feature] Badge 컴포넌트 구현
  frontend/src/components/Badge/Badge.stories.ts
  frontend/src/components/Badge/index.css.ts
  frontend/src/components/Badge/index.tsx
  frontend/src/components/Icon/component/CalendarCheck.tsx
  frontend/src/components/Icon/component/Clock.tsx
  frontend/src/components/Icon/component/PinLocation.tsx
  frontend/src/components/Icon/component/UserTwo.tsx
  frontend/src/components/Icon/index.ts
  frontend/src/components/Icon/svg/calendar-check.svg
  frontend/src/components/Icon/svg/clock.svg
  frontend/src/components/Icon/svg/pin-location.svg
  frontend/src/components/Icon/svg/user-two.svg
Labels: 🖥️ FE

#134 [FE-Feat] Date Picker 리팩터링
  frontend/src/components/Calendar/context/SharedCalendarContext.ts
  frontend/src/components/DatePicker/DatePicker.stories.tsx
  frontend/src/components/DatePicker/DatePickerContext.ts
  frontend/src/components/DatePicker/DatePickerRange.tsx
  frontend/src/components/DatePicker/DatePickerSelect.tsx
  frontend/src/components/DatePicker/Header/index.css.ts
  frontend/src/components/DatePicker/Header/index.tsx
  frontend/src/components/DatePicker/RootContainer.tsx
  frontend/src/components/DatePicker/Table/Cell/CellWrapper.tsx
  frontend/src/components/DatePicker/Table/Cell/DateCell.tsx
  frontend/src/components/DatePicker/Table/Cell/index.css.ts
  frontend/src/components/DatePicker/Table/Highlight/index.css.ts
  frontend/src/components/DatePicker/Table/Highlight/index.ts
  frontend/src/components/DatePicker/Table/Row.tsx
  frontend/src/components/DatePicker/Table/TableBody.tsx
  frontend/src/components/DatePicker/Table/index.css.ts
  frontend/src/components/DatePicker/Table/index.tsx
  frontend/src/components/DatePicker/context/DatePickerContext.ts
  frontend/src/components/DatePicker/context/DatePickerRangeProvider.tsx
  frontend/src/components/DatePicker/context/DatePickerSelectProvider.tsx
  frontend/src/components/DatePicker/datePicker.stories.css.ts
  frontend/src/components/DatePicker/index.css.ts
  frontend/src/components/DatePicker/index.tsx
  frontend/src/hooks/useDatePicker/index.ts
  frontend/src/hooks/useDatePicker/useDatePickerRange.ts
  frontend/src/hooks/useDatePicker/useDatePickerSelect.ts
  frontend/src/hooks/useDatePicker/useDateSelect.ts
  frontend/src/hooks/useDatePicker/useHighlightRange.ts
  frontend/src/hooks/useDatePicker/useMonthNavigation.ts
  frontend/src/hooks/useSharedCalendar.ts
Labels: 🖥️ FE

#141 [BE-Feat] CORS 설정 추가
  backend/src/main/java/endolphin/backend/global/config/WebConfig.java
  backend/src/test/resources/application.yml
Labels: 🛠️ BE

#139 [BE-Feat] 캘린더 api 사용 로직 구현
  backend/src/main/java/endolphin/backend/domain/auth/AuthService.java
  backend/src/main/java/endolphin/backend/domain/calendar/CalendarRepository.java
  backend/src/main/java/endolphin/backend/domain/calendar/CalendarService.java
  backend/src/main/java/endolphin/backend/domain/calendar/entity/Calendar.java
  backend/src/main/java/endolphin/backend/domain/user/UserService.java
  backend/src/main/java/endolphin/backend/global/config/GoogleCalendarUrl.java
  backend/src/main/java/endolphin/backend/global/google/GoogleCalendarService.java
  backend/src/main/java/endolphin/backend/global/google/dto/GoogleEvent.java
  backend/src/test/java/endolphin/backend/domain/auth/AuthServiceTest.java
  backend/src/test/java/endolphin/backend/domain/calendar/CalendarServiceTest.java
Labels: 🛠️ BE

#135 [FE-Feat] 일정 초대 페이지 마크업
  frontend/src/components/Button/index.css.ts
  frontend/src/components/Button/index.tsx
  frontend/src/components/DatePicker/DatePicker.stories.tsx
  frontend/src/components/DatePicker/Header/index.tsx
  frontend/src/features/discussion/ui/DiscussionInviteCard/Badges.tsx
  frontend/src/features/discussion/ui/DiscussionInviteCard/index.css.ts
  frontend/src/features/discussion/ui/DiscussionInviteCard/index.tsx
  frontend/src/hooks/useDatePicker/useDatePickerSelect.ts
  frontend/src/pages/DiscussionInvitePage/index.css.ts
  frontend/src/pages/DiscussionInvitePage/index.tsx
  frontend/src/routeTree.gen.ts
  frontend/src/routes/discussion/invite/$id.tsx
  frontend/src/utils/date/calendar/index.ts
  frontend/src/utils/date/date.ts
  frontend/src/utils/date/time.ts
Labels: 🖥️ FE

#142 [BE-Feat] 후보 일정 전처리 구현
  backend/src/main/java/endolphin/backend/domain/discussion/DiscussionParticipantRepository.java
  backend/src/main/java/endolphin/backend/domain/discussion/DiscussionParticipantService.java
  backend/src/main/java/endolphin/backend/domain/discussion/DiscussionService.java
  backend/src/main/java/endolphin/backend/domain/discussion/entity/DiscussionParticipant.java
  backend/src/main/java/endolphin/backend/domain/personal_event/PersonalEventPreprocessor.java
  backend/src/main/java/endolphin/backend/domain/personal_event/PersonalEventRepository.java
  backend/src/main/java/endolphin/backend/domain/personal_event/PersonalEventService.java
  backend/src/main/java/endolphin/backend/global/error/exception/ErrorCode.java
  backend/src/main/java/endolphin/backend/global/redis/DiscussionBitmapService.java
  backend/src/test/java/endolphin/backend/domain/personal_event/PersonalEventPreprocessorTest.java
  backend/src/test/java/endolphin/backend/domain/personal_event/PersonalEventRepositoryTest.java
  backend/src/test/java/endolphin/backend/global/redis/DiscussionBitmapServiceTest.java
Labels: 🛠️ BE

#147 [BE-Fix] 테스트 설정 파일 추가
  backend/src/test/resources/application.yml
Labels: 🛠️ BE

#151 [BE-Fix] 구글 로그인 시 프론트 엔드로 리다이렉션 하도록 수정
  backend/src/main/java/endolphin/backend/domain/auth/AuthController.java
  backend/src/test/resources/application.yml
Labels: 🛠️ BE

#154 [FE-Feat] 로그인 화면 및 기능 구현
  frontend/eslint.config.js
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/src/components/Icon/png/google-login-icon.png
  frontend/src/components/Input/MultiInput.tsx
  frontend/src/features/login/api/index.ts
  frontend/src/features/login/model/index.ts
  frontend/src/layout/GlobalNavBar/index.tsx
  frontend/src/pages/LandingPage/index.tsx
  frontend/src/pages/LoginPage/index.css.ts
  frontend/src/pages/LoginPage/index.tsx
  frontend/src/routeTree.gen.ts
  frontend/src/routes/__root.tsx
  frontend/src/routes/login/index.lazy.tsx
  frontend/src/routes/oauth.redirect/index.lazy.tsx
  frontend/src/utils/fetch/index.ts
  frontend/src/utils/jsx/index.tsx
  frontend/src/utils/route/index.ts
Labels: 🖥️ FE

#158 [FE-Feat] 내 일정 관리 페이지 마크업
  frontend/src/components/Calendar/Calendar.stories.tsx
  frontend/src/components/Calendar/Core/CalendarHeader.tsx
  frontend/src/components/Calendar/Core/TimeControl.tsx
  frontend/src/components/Calendar/Core/index.css.ts
  frontend/src/components/Calendar/Core/index.tsx
  frontend/src/components/Calendar/Header/index.css.ts
  frontend/src/components/Calendar/Table/CalendarDay.tsx
  frontend/src/components/Calendar/Table/CalendarDetailCell.tsx
  frontend/src/components/Calendar/Table/CalendarSide.tsx
  frontend/src/components/Calendar/Table/index.css.ts
  frontend/src/components/Calendar/Table/index.tsx
  frontend/src/components/Calendar/context/CalendarProvider.tsx
  frontend/src/components/Calendar/context/SharedCalendarContext.ts
  frontend/src/components/Calendar/context/TimeTableProvider.tsx
  frontend/src/components/Calendar/index.css.ts
  frontend/src/components/Calendar/index.tsx
  frontend/src/components/DatePicker/DatePickerRange.tsx
  frontend/src/components/DatePicker/DatePickerSelect.tsx
  frontend/src/components/DatePicker/context/DatePickerSelectProvider.tsx
  frontend/src/components/DatePicker/index.css.ts
  frontend/src/constants/date.ts
  frontend/src/features/my-calendar/model/index.ts
  frontend/src/features/my-calendar/ui/CalendarCard/CardBottom.tsx
  frontend/src/features/my-calendar/ui/CalendarCard/index.css.ts
  frontend/src/features/my-calendar/ui/CalendarCard/index.tsx
  frontend/src/features/my-calendar/ui/CalendarCardList/index.tsx
  frontend/src/features/my-calendar/ui/MyCalendar/index.css.ts
  frontend/src/features/my-calendar/ui/MyCalendar/index.tsx
  frontend/src/features/my-calendar/ui/MyDatePicker/index.css.ts
  frontend/src/features/my-calendar/ui/MyDatePicker/index.tsx
  frontend/src/features/my-calendar/ui/SchedulePopover/PopoverButton.tsx
  frontend/src/features/my-calendar/ui/SchedulePopover/PopoverForm.tsx
  frontend/src/features/my-calendar/ui/SchedulePopover/Title.tsx
  frontend/src/features/my-calendar/ui/SchedulePopover/index.css.ts
  frontend/src/features/my-calendar/ui/SchedulePopover/index.tsx
  frontend/src/features/my-schedule/ui/CalendarCard/CardBottom.tsx
  frontend/src/features/my-schedule/ui/CalendarCard/index.css.ts
  frontend/src/features/my-schedule/ui/CalendarCard/index.tsx
  frontend/src/features/my-schedule/ui/SchedulePopover/PopoverForm.tsx
  frontend/src/features/my-schedule/ui/SchedulePopover/index.tsx
  frontend/src/hooks/useCalendar.ts
  frontend/src/hooks/useDatePicker/useDatePickerSelect.ts
  frontend/src/hooks/useSelectTime.ts
  frontend/src/layout/GlobalNavBar/buttons/MyCalendarLink.tsx
  frontend/src/layout/GlobalNavBar/buttons/NewDiscussionLink.tsx
  frontend/src/layout/GlobalNavBar/buttons/index.ts
  frontend/src/layout/GlobalNavBar/index.tsx
  frontend/src/pages/MyCalendarPage/index.css.ts
  frontend/src/pages/MyCalendarPage/index.tsx
  frontend/src/pages/MySchedulePage/index.tsx
  frontend/src/routeTree.gen.ts
  frontend/src/routes/discussion/create/$id.tsx
  frontend/src/routes/discussion/create/index.tsx
  frontend/src/routes/discussion/edit/$id.tsx
  frontend/src/routes/discussion/invite/$id.tsx
  frontend/src/routes/my-calendar/index.lazy.tsx
  frontend/src/utils/common/index.ts
  frontend/src/utils/date/date.ts
  frontend/src/utils/date/position.ts
  frontend/src/utils/date/time.ts
Labels: 🖥️ FE

#159 [FE-Feat] 홈 화면 마크업
  frontend/src/components/Button/index.css.ts
  frontend/src/components/Chip/index.css.ts
  frontend/src/components/Chip/index.tsx
  frontend/src/components/Pagination/index.tsx
  frontend/src/components/SegmentControl/index.tsx
  frontend/src/features/shared-schedule/model/index.ts
  frontend/src/features/shared-schedule/ui/ExpiredSchedules/ExpiredScheduleList.tsx
  frontend/src/features/shared-schedule/ui/ExpiredSchedules/ExpiredScheduleListItem.tsx
  frontend/src/features/shared-schedule/ui/ExpiredSchedules/expiredScheduleList.css.ts
  frontend/src/features/shared-schedule/ui/ExpiredSchedules/expiredScheduleListItem.css.ts
  frontend/src/features/shared-schedule/ui/ExpiredSchedules/index.css.ts
  frontend/src/features/shared-schedule/ui/ExpiredSchedules/index.tsx
  frontend/src/features/shared-schedule/ui/UnConfirmedSchedules/ScheduleDetails.css.ts
  frontend/src/features/shared-schedule/ui/UnConfirmedSchedules/ScheduleDetails.tsx
  frontend/src/features/shared-schedule/ui/UnConfirmedSchedules/UnconfirmedScheduleList.tsx
  frontend/src/features/shared-schedule/ui/UnConfirmedSchedules/UnconfirmedScheduleListItem.tsx
  frontend/src/features/shared-schedule/ui/UnConfirmedSchedules/index.css.ts
  frontend/src/features/shared-schedule/ui/UnConfirmedSchedules/index.tsx
  frontend/src/features/shared-schedule/ui/UnConfirmedSchedules/unconfirmedScheduleList.css.ts
  frontend/src/features/shared-schedule/ui/UnConfirmedSchedules/unconfirmedscheduleListItem.css.ts
  frontend/src/features/shared-schedule/ui/UpcomingSchedules/ControlButton.tsx
  frontend/src/features/shared-schedule/ui/UpcomingSchedules/ScheduleCard.tsx
  frontend/src/features/shared-schedule/ui/UpcomingSchedules/UpcomingCarousel.css.ts
  frontend/src/features/shared-schedule/ui/UpcomingSchedules/UpcomingCarousel.tsx
  frontend/src/features/shared-schedule/ui/UpcomingSchedules/UpcomingScheduleList.tsx
  frontend/src/features/shared-schedule/ui/UpcomingSchedules/UpcomingScheduleListItem.tsx
  frontend/src/features/shared-schedule/ui/UpcomingSchedules/index.css.ts
  frontend/src/features/shared-schedule/ui/UpcomingSchedules/index.tsx
  frontend/src/features/shared-schedule/ui/UpcomingSchedules/scheduleCard.css.ts
  frontend/src/features/shared-schedule/ui/UpcomingSchedules/upcomingScheduleList.css.ts
  frontend/src/features/shared-schedule/ui/UpcomingSchedules/upcomingScheduleListItem.css.ts
  frontend/src/hooks/useCarousel.ts
  frontend/src/layout/GlobalNavBar/buttons/NewDiscussionLink.tsx
  frontend/src/layout/GlobalNavBar/index.css.ts
  frontend/src/layout/GlobalNavBar/index.tsx
  frontend/src/layout/MainLayout/index.css.ts
  frontend/src/layout/MainLayout/index.tsx
  frontend/src/pages/HomePage/index.css.ts
  frontend/src/pages/HomePage/index.tsx
  frontend/src/pages/UpcomingSchedulePage/index.css.ts
  frontend/src/pages/UpcomingSchedulePage/index.tsx
  frontend/src/routeTree.gen.ts
  frontend/src/routes/_main/home/index.lazy.tsx
  frontend/src/routes/_main/upcoming-schedule/index.lazy.tsx
  frontend/src/routes/discussion/create/$id.tsx
  frontend/src/routes/landing/index.tsx
  frontend/src/theme/color.ts
  frontend/src/theme/gradient.ts
  frontend/src/theme/radius.ts
  frontend/src/theme/spacing.ts
  frontend/src/theme/typo.ts
Labels: 🖥️ FE

#163 [BE-Feat] 현재 로그인한 사용자 정보 반환 기능 구현
  backend/src/main/java/endolphin/backend/domain/user/UserController.java
  backend/src/main/java/endolphin/backend/domain/user/dto/CurrentUserInfo.java
Labels: 🛠️ BE

#153 [BE-Feat] 후보 일정 검색 api 구현
  backend/src/main/java/endolphin/backend/domain/candidate_event/CandidateEventService.java
  backend/src/main/java/endolphin/backend/domain/candidate_event/dto/CalendarViewRequest.java
  backend/src/main/java/endolphin/backend/domain/candidate_event/dto/CalendarViewResponse.java
  backend/src/main/java/endolphin/backend/domain/candidate_event/dto/CandidateEvent.java
  backend/src/main/java/endolphin/backend/domain/candidate_event/dto/CandidateEventResponse.java
  backend/src/main/java/endolphin/backend/domain/candidate_event/dto/RankViewRequest.java
  backend/src/main/java/endolphin/backend/domain/candidate_event/dto/RankViewResponse.java
  backend/src/main/java/endolphin/backend/domain/discussion/DiscussionController.java
  backend/src/main/java/endolphin/backend/domain/discussion/DiscussionParticipantRepository.java
  backend/src/main/java/endolphin/backend/domain/discussion/DiscussionParticipantService.java
  backend/src/main/java/endolphin/backend/domain/discussion/DiscussionService.java
  backend/src/main/java/endolphin/backend/domain/discussion/entity/DiscussionParticipant.java
  backend/src/main/java/endolphin/backend/domain/personal_event/PersonalEventPreprocessor.java
  backend/src/main/java/endolphin/backend/domain/personal_event/PersonalEventRepository.java
  backend/src/main/java/endolphin/backend/domain/user/UserRepository.java
  backend/src/main/java/endolphin/backend/domain/user/UserService.java
  backend/src/main/java/endolphin/backend/domain/user/dto/UserIdNameDto.java
  backend/src/main/java/endolphin/backend/global/error/exception/ErrorCode.java
  backend/src/main/java/endolphin/backend/global/redis/DiscussionBitmapService.java
  backend/src/test/java/endolphin/backend/domain/candidate_event/CandidateEventServiceTest.java
  backend/src/test/java/endolphin/backend/domain/discussion/DiscussionParticipantServiceTest.java
  backend/src/test/java/endolphin/backend/domain/personal_event/PersonalEventPreprocessorTest.java
  backend/src/test/java/endolphin/backend/global/redis/DiscussionBitmapServiceTest.java
Labels: 🛠️ BE

#156 [BE-Feat] 논의 생성 api에 비밀번호 추가
  backend/src/main/java/endolphin/backend/domain/discussion/DiscussionService.java
  backend/src/main/java/endolphin/backend/domain/discussion/dto/CreateDiscussionRequest.java
  backend/src/main/java/endolphin/backend/domain/discussion/entity/Discussion.java
  backend/src/main/java/endolphin/backend/global/error/exception/ErrorCode.java
  backend/src/main/java/endolphin/backend/global/security/PasswordEncoder.java
  backend/src/test/java/endolphin/backend/domain/discussion/DiscussionControllerTest.java
  backend/src/test/java/endolphin/backend/domain/discussion/DiscussionServiceTest.java
  backend/src/test/java/endolphin/backend/global/security/PasswordEncoderTest.java
  backend/src/test/resources/application.yml
Labels: 🛠️ BE

#165 [BE-Fix] 필요없는 googleEventId 삭제
  backend/src/main/java/endolphin/backend/domain/personal_event/dto/PersonalEventResponse.java
  backend/src/test/java/endolphin/backend/domain/personal_event/PersonalEventControllerTest.java
Labels: 🛠️ BE

#150 [BE-Feat] 구글 캘린더로 가져온 일정들을 서비스에 반영하는 기능 구현
  backend/src/main/java/endolphin/backend/domain/auth/AuthService.java
  backend/src/main/java/endolphin/backend/domain/calendar/CalendarRepository.java
  backend/src/main/java/endolphin/backend/domain/calendar/CalendarService.java
  backend/src/main/java/endolphin/backend/domain/discussion/DiscussionParticipantRepository.java
  backend/src/main/java/endolphin/backend/domain/discussion/DiscussionParticipantService.java
  backend/src/main/java/endolphin/backend/domain/personal_event/PersonalEventPreprocessor.java
  backend/src/main/java/endolphin/backend/domain/personal_event/PersonalEventRepository.java
  backend/src/main/java/endolphin/backend/domain/personal_event/PersonalEventService.java
  backend/src/main/java/endolphin/backend/domain/personal_event/entity/PersonalEvent.java
  backend/src/main/java/endolphin/backend/global/error/exception/ErrorCode.java
  backend/src/main/java/endolphin/backend/global/google/GoogleCalendarService.java
  backend/src/main/java/endolphin/backend/global/google/dto/GoogleEvent.java
  backend/src/main/java/endolphin/backend/global/google/enums/GoogleEventStatus.java
  backend/src/main/java/endolphin/backend/global/google/enums/GoogleResourceState.java
  backend/src/test/java/endolphin/backend/domain/auth/AuthServiceTest.java
  backend/src/test/java/endolphin/backend/domain/personal_event/PersonalEventPreprocessorTest.java
  backend/src/test/java/endolphin/backend/domain/personal_event/PersonalEventServiceTest.java
  backend/src/test/java/endolphin/backend/global/google/GoogleCalendarServiceTest.java
Labels: 🛠️ BE

#168 [FE-Feat] 라우팅 정리 및 express 서버 세팅
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/server/cookies.js
  frontend/server/index.js
  frontend/src/apis/index.ts
  frontend/src/components/DatePicker/DatePickerRange.tsx
  frontend/src/components/DatePicker/DatePickerSelect.tsx
  frontend/src/components/DatePicker/index.css.ts
  frontend/src/features/discussion/ui/DiscussionCreateCard/index.tsx
  frontend/src/features/discussion/ui/DiscussionForm/FormButton.tsx
  frontend/src/features/discussion/ui/DiscussionTitle/index.tsx
  frontend/src/features/shared-schedule/ui/UpcomingSchedules/index.tsx
  frontend/src/layout/GlobalNavBar/index.tsx
  frontend/src/layout/MainLayout/index.css.ts
  frontend/src/routeTree.gen.ts
  frontend/src/routes/_main/discussion/edit/$id.tsx
  frontend/src/routes/discussion/create/$id.tsx
  frontend/src/routes/index.tsx
Labels: 🖥️ FE

#170 [BE-Fix] 구글 이벤트 동기화 버그 수정
  backend/src/main/java/endolphin/backend/global/google/GoogleCalendarService.java
Labels: 🛠️ BE

#171 [BE-Fix] 구글 이벤트 상태에 null이 들어가는 버그 수정
  backend/src/main/java/endolphin/backend/global/google/GoogleCalendarService.java
Labels: 🛠️ BE

#169 [FE-Feat] 개인 일정 생성, 조회
  frontend/src/features/discussion/ui/DiscussionRank/index.tsx
  frontend/src/features/discussion/ui/DiscussionTab/index.tsx
  frontend/src/features/my-calendar/api/index.ts
  frontend/src/features/my-calendar/api/keys.ts
  frontend/src/features/my-calendar/api/mutations.ts
  frontend/src/features/my-calendar/api/queries.ts
  frontend/src/features/my-calendar/model/index.ts
  frontend/src/features/my-calendar/ui/CalendarCardList/index.tsx
  frontend/src/features/my-calendar/ui/MyCalendar/index.tsx
  frontend/src/features/my-calendar/ui/SchedulePopover/PopoverForm.tsx
  frontend/src/features/my-calendar/ui/SchedulePopover/index.tsx
  frontend/src/hooks/useFormRef.ts
  frontend/src/pages/DiscussionPage/DiscussionCreateFinishPage/index.css.ts
  frontend/src/pages/DiscussionPage/DiscussionCreateFinishPage/index.tsx
  frontend/src/pages/DiscussionPage/DiscussionInvitePage/index.css.ts
  frontend/src/pages/DiscussionPage/DiscussionInvitePage/index.tsx
  frontend/src/routes/_main/discussion/invite/$id.tsx
  frontend/src/routes/discussion/create/$id.tsx
  frontend/src/utils/date/date.ts
  frontend/src/utils/date/format.ts
  frontend/src/utils/fetch/index.ts
Labels: 🖥️ FE

#172 [BE-Fix] 쿠키 삭제, 인증 헤더 사용으로 변경
  backend/src/main/java/endolphin/backend/domain/auth/AuthController.java
  backend/src/main/java/endolphin/backend/domain/auth/AuthService.java
  backend/src/main/java/endolphin/backend/domain/auth/dto/LoginRequest.java
  backend/src/main/java/endolphin/backend/global/security/JwtAuthFilter.java
  backend/src/test/java/endolphin/backend/domain/auth/AuthServiceTest.java
Labels: 🛠️ BE

#175 [BE-Fix] 로그인 url을 jwt 인증 필터에서 제외
  backend/src/main/java/endolphin/backend/domain/auth/AuthController.java
  backend/src/main/java/endolphin/backend/domain/auth/dto/UrlResponse.java
  backend/src/main/java/endolphin/backend/global/google/GoogleController.java
  backend/src/main/java/endolphin/backend/global/google/GoogleOAuthService.java
  backend/src/main/java/endolphin/backend/global/security/JwtAuthFilter.java
  backend/src/test/java/endolphin/backend/global/google/GoogleOAuthServiceTest.java
Labels: 🛠️ BE

#173 [BE-Fix] 개인 일정 조정 가능 여부 설정 버그 수정
  backend/src/main/java/endolphin/backend/domain/personal_event/PersonalEventService.java
  backend/src/main/java/endolphin/backend/domain/personal_event/entity/PersonalEvent.java
Labels: 🛠️ BE

#167 [BE-Fix] 개인 일정 조회 파라미터를 api명세에 맞게 수정
  backend/src/main/java/endolphin/backend/domain/personal_event/PersonalEventController.java
  backend/src/main/java/endolphin/backend/domain/personal_event/PersonalEventService.java
  backend/src/test/java/endolphin/backend/domain/personal_event/PersonalEventServiceTest.java
Labels: 🛠️ BE

#157 [BE-Feat] 후보 일정 상세 정보 보기 기능 구현
  backend/src/main/java/endolphin/backend/domain/discussion/DiscussionController.java
  backend/src/main/java/endolphin/backend/domain/discussion/DiscussionParticipantRepository.java
  backend/src/main/java/endolphin/backend/domain/discussion/DiscussionParticipantService.java
  backend/src/main/java/endolphin/backend/domain/discussion/DiscussionService.java
  backend/src/main/java/endolphin/backend/domain/discussion/dto/CandidateEventDetailsRequest.java
  backend/src/main/java/endolphin/backend/domain/discussion/dto/CandidateEventDetailsResponse.java
  backend/src/main/java/endolphin/backend/domain/discussion/entity/DiscussionParticipant.java
  backend/src/main/java/endolphin/backend/domain/personal_event/PersonalEventRepository.java
  backend/src/main/java/endolphin/backend/domain/personal_event/PersonalEventService.java
  backend/src/main/java/endolphin/backend/domain/personal_event/dto/PersonalEventWithStatus.java
  backend/src/main/java/endolphin/backend/domain/personal_event/enums/PersonalEventStatus.java
  backend/src/main/java/endolphin/backend/domain/user/dto/UserInfoWithPersonalEvents.java
  backend/src/main/java/endolphin/backend/global/error/exception/ErrorCode.java
  backend/src/test/java/endolphin/backend/domain/discussion/DiscussionServiceTest.java
  backend/src/test/java/endolphin/backend/domain/personal_event/PersonalEventRepositoryTest.java
  backend/src/test/java/endolphin/backend/domain/personal_event/PersonalEventServiceTest.java
Labels: 🛠️ BE

#182 [BE-Fix] 재로그인 버그 수정
  backend/src/main/java/endolphin/backend/domain/personal_event/PersonalEventService.java
  backend/src/main/java/endolphin/backend/domain/personal_event/entity/PersonalEvent.java
  backend/src/main/java/endolphin/backend/global/config/GoogleCalendarProperties.java
  backend/src/main/java/endolphin/backend/global/config/GoogleCalendarUrl.java
  backend/src/main/java/endolphin/backend/global/google/GoogleCalendarService.java
  backend/src/test/java/endolphin/backend/global/google/GoogleCalendarServiceTest.java
  backend/src/test/resources/application.yml
Labels: 🛠️ BE

#152 [BE-Feat] 개인 일정 전처리 과정의 테스트 케이스 추가
  backend/src/test/java/endolphin/backend/domain/personal_event/PersonalEventPreprocessorTest.java
Labels: 🛠️ BE

#183 [BE-Fix] DiscussionParticipant 레포지토리의 fetch join 삭제
  backend/src/main/java/endolphin/backend/domain/discussion/DiscussionParticipantRepository.java
  backend/src/main/java/endolphin/backend/domain/discussion/DiscussionParticipantService.java
  backend/src/main/java/endolphin/backend/domain/discussion/DiscussionService.java
  backend/src/test/java/endolphin/backend/domain/discussion/DiscussionServiceTest.java
Labels: 🛠️ BE

#181 [FE-Feat] 로그인 토큰 쿠키가 아닌 헤더로 보내도록 변경
  frontend/server/index.js
  frontend/src/envconfig.ts
  frontend/src/features/login/api/index.ts
  frontend/src/features/login/api/mutations.ts
  frontend/src/features/login/model/index.ts
  frontend/src/pages/DiscussionPage/DiscussionCreateFinishPage/index.css.ts
  frontend/src/pages/DiscussionPage/DiscussionCreateFinishPage/index.tsx
  frontend/src/pages/LoginPage/index.tsx
  frontend/src/pages/MyCalendarPage/index.css.ts
  frontend/src/routeTree.gen.ts
  frontend/src/routes/_main.tsx
  frontend/src/routes/_main/discussion/create/$id.tsx
  frontend/src/routes/_main/my-calendar/index.lazy.tsx
  frontend/src/routes/index.tsx
  frontend/src/routes/oauth.redirect/index.lazy.tsx
  frontend/src/routes/oauth.redirect/index.tsx
  frontend/src/utils/auth/index.ts
  frontend/src/utils/fetch/index.ts
Labels: 🖥️ FE

#161 [BE-Feat] ci 파일 추가
  .github/workflows/be-ci.yml
Labels: 🛠️ BE

#186 [BE-Feat] 논의 참여자 목록 조회 api, 내가 호스트인가요? api 구현
  backend/src/main/java/endolphin/backend/domain/discussion/DiscussionController.java
  backend/src/main/java/endolphin/backend/domain/discussion/DiscussionParticipantRepository.java
  backend/src/main/java/endolphin/backend/domain/discussion/DiscussionParticipantService.java
  backend/src/main/java/endolphin/backend/domain/discussion/dto/DiscussionParticipantsResponse.java
  backend/src/main/java/endolphin/backend/domain/discussion/entity/DiscussionParticipant.java
  backend/src/test/java/endolphin/backend/domain/discussion/DiscussionParticipantRepositoryTest.java
Labels: 🛠️ BE

#180 [BE-Feat] 논의 정보 조회, 초대장 정보 조회 API 구현
  backend/src/main/java/endolphin/backend/domain/discussion/DiscussionController.java
  backend/src/main/java/endolphin/backend/domain/discussion/DiscussionParticipantRepository.java
  backend/src/main/java/endolphin/backend/domain/discussion/DiscussionParticipantService.java
  backend/src/main/java/endolphin/backend/domain/discussion/DiscussionService.java
  backend/src/main/java/endolphin/backend/domain/discussion/dto/DiscussionInfo.java
  backend/src/main/java/endolphin/backend/domain/discussion/dto/InvitationInfo.java
  backend/src/main/java/endolphin/backend/global/error/exception/ErrorCode.java
  backend/src/main/java/endolphin/backend/global/security/JwtAuthFilter.java
  backend/src/test/java/endolphin/backend/domain/discussion/DiscussionParticipantServiceTest.java
  backend/src/test/java/endolphin/backend/domain/discussion/DiscussionServiceTest.java
Labels: 🛠️ BE

#176 [BE-Feat] 논의 참여(초대 수락) API 구현
  backend/src/main/java/endolphin/backend/domain/discussion/DiscussionController.java
  backend/src/main/java/endolphin/backend/domain/discussion/DiscussionService.java
  backend/src/main/java/endolphin/backend/domain/discussion/dto/CreateDiscussionRequest.java
  backend/src/main/java/endolphin/backend/domain/discussion/dto/JoinDiscussionRequest.java
  backend/src/main/java/endolphin/backend/domain/discussion/dto/JoinDiscussionResponse.java
  backend/src/main/java/endolphin/backend/global/config/RedisConfig.java
  backend/src/main/java/endolphin/backend/global/error/exception/ErrorCode.java
  backend/src/main/java/endolphin/backend/global/redis/PasswordCountService.java
  backend/src/test/java/endolphin/backend/domain/discussion/DiscussionServiceTest.java
  backend/src/test/java/endolphin/backend/global/redis/PasswordCountServiceTest.java
Labels: 🛠️ BE

#191 [BE-Fix] 논의 생성 버그 수정
  backend/src/main/java/endolphin/backend/domain/discussion/DiscussionService.java
  backend/src/main/java/endolphin/backend/domain/discussion/entity/Discussion.java
Labels: 🛠️ BE

#188 [BE-Feat] 확정되지 않은 일정 조회 api 구현
  backend/src/main/java/endolphin/backend/domain/discussion/DiscussionParticipantRepository.java
  backend/src/main/java/endolphin/backend/domain/discussion/DiscussionParticipantService.java
  backend/src/main/java/endolphin/backend/domain/discussion/DiscussionService.java
  backend/src/main/java/endolphin/backend/domain/discussion/dto/OngoingDiscussion.java
  backend/src/main/java/endolphin/backend/domain/discussion/dto/OngoingDiscussionsResponse.java
  backend/src/main/java/endolphin/backend/domain/discussion/enums/AttendType.java
  backend/src/main/java/endolphin/backend/domain/shared_event/SharedEventController.java
  backend/src/main/java/endolphin/backend/global/util/TimeCalculator.java
  backend/src/test/java/endolphin/backend/domain/discussion/DiscussionParticipantRepositoryTest.java
  backend/src/test/java/endolphin/backend/domain/discussion/DiscussionParticipantServiceTest.java
Labels: 🛠️ BE

#184 [FE-Feat] 후보 일정 상세 화면 구현
  frontend/.gitignore
  frontend/src/components/Icon/component/Close.tsx
  frontend/src/components/Icon/index.ts
  frontend/src/components/Icon/svg/close.svg
  frontend/src/constants/regex.ts
  frontend/src/features/candidate-schedule/model/index.ts
  frontend/src/features/candidate-schedule/ui/Header.tsx
  frontend/src/features/candidate-schedule/ui/TImelineCanvas/ConflictRangeBox.tsx
  frontend/src/features/candidate-schedule/ui/TImelineCanvas/TimelineBlocks.tsx
  frontend/src/features/candidate-schedule/ui/TImelineCanvas/TimelineColumns.tsx
  frontend/src/features/candidate-schedule/ui/TImelineCanvas/index.css.ts
  frontend/src/features/candidate-schedule/ui/TImelineCanvas/index.tsx
  frontend/src/features/candidate-schedule/ui/TimelineContent/ChipAble.tsx
  frontend/src/features/candidate-schedule/ui/TimelineContent/ParticipantList.tsx
  frontend/src/features/candidate-schedule/ui/TimelineContent/chipAble.css.ts
  frontend/src/features/candidate-schedule/ui/TimelineContent/index.css.ts
  frontend/src/features/candidate-schedule/ui/TimelineContent/index.tsx
  frontend/src/features/candidate-schedule/ui/TimelineContent/participantList.css.ts
  frontend/src/features/candidate-schedule/ui/index.css.ts
  frontend/src/features/candidate-schedule/ui/index.tsx
  frontend/src/features/candidate-schedule/ui/timelineHelper.ts
  frontend/src/features/discussion/model/index.ts
  frontend/src/features/discussion/ui/DiscussionCard/index.tsx
  frontend/src/features/discussion/ui/DiscussionForm/MeetingDurationDropdown.tsx
  frontend/src/features/discussion/ui/DiscussionForm/MeetingTimeDropdowns.tsx
  frontend/src/features/my-calendar/ui/CalendarCard/index.tsx
  frontend/src/features/my-calendar/ui/SchedulePopover/PopoverForm.tsx
  frontend/src/pages/CandidateSchedulePage/index.css.ts
  frontend/src/pages/CandidateSchedulePage/index.tsx
  frontend/src/routeTree.gen.ts
  frontend/src/routes/discussion/candidate/index.lazy.tsx
  frontend/src/utils/date/format.ts
  frontend/src/utils/date/time.ts
  frontend/src/utils/index.ts
  frontend/src/utils/zod/index.ts
Labels: 🖥️ FE

#194 [ALL-Feat] 배포 스크립트 작성
  .github/workflows/be-cd.yml
  .github/workflows/be-ci.yml
  .github/workflows/fe-cd.yml
  backend/src/main/java/endolphin/backend/domain/auth/AuthController.java
  backend/src/main/java/endolphin/backend/global/health/HealthController.java
  backend/src/main/java/endolphin/backend/global/security/JwtAuthFilter.java
Labels: 🔮 ALL

#197 [ALL-Fix] github actions 버그 수정
  .github/workflows/be-cd.yml
  .github/workflows/fe-cd.yml
Labels: 🔮 ALL

#189 [FE-Feat] 내 일정 관리 페이지 개인 일정 수정, 삭제
  frontend/src/components/Calendar/Table/CalendarDetailCell.tsx
  frontend/src/components/Calendar/Table/index.tsx
  frontend/src/components/Checkbox/CheckboxInput.tsx
  frontend/src/components/Checkbox/CheckboxLabel.tsx
  frontend/src/components/Checkbox/index.tsx
  frontend/src/components/Checkbox/type.ts
  frontend/src/features/login/api/mutations.ts
  frontend/src/features/my-calendar/api/hooks.ts
  frontend/src/features/my-calendar/api/index.ts
  frontend/src/features/my-calendar/api/keys.ts
  frontend/src/features/my-calendar/api/mutations.ts
  frontend/src/features/my-calendar/api/queries.ts
  frontend/src/features/my-calendar/model/index.ts
  frontend/src/features/my-calendar/ui/CalendarCard/Card.tsx
  frontend/src/features/my-calendar/ui/CalendarCard/CardBottom.tsx
  frontend/src/features/my-calendar/ui/CalendarCard/CardContents.tsx
  frontend/src/features/my-calendar/ui/CalendarCard/index.css.ts
  frontend/src/features/my-calendar/ui/CalendarCard/index.tsx
  frontend/src/features/my-calendar/ui/CalendarCard/type.ts
  frontend/src/features/my-calendar/ui/CalendarCardList/index.tsx
  frontend/src/features/my-calendar/ui/MyCalendar/index.tsx
  frontend/src/features/my-calendar/ui/SchedulePopover/PopoverButton.tsx
  frontend/src/features/my-calendar/ui/SchedulePopover/PopoverForm.tsx
  frontend/src/features/my-calendar/ui/SchedulePopover/index.css.ts
  frontend/src/features/my-calendar/ui/SchedulePopover/index.tsx
  frontend/src/hooks/useCheckbox.ts
  frontend/src/hooks/useFormRef.ts
  frontend/src/hooks/useSelectTime.ts
  frontend/src/routes/oauth.redirect/index.tsx
  frontend/src/utils/fetch/index.ts
Labels: 🖥️ FE

#179 [BE-Feat] 논의 상태 변경 scheduler 구현
  backend/src/main/java/endolphin/backend/domain/discussion/DiscussionRepository.java
  backend/src/main/java/endolphin/backend/domain/shared_event/SharedEventRepository.java
  backend/src/main/java/endolphin/backend/domain/shared_event/SharedEventService.java
  backend/src/main/java/endolphin/backend/global/config/EnableSchedulingConfig.java
  backend/src/main/java/endolphin/backend/global/scheduler/DiscussionStatusScheduler.java
  backend/src/test/java/endolphin/backend/domain/shared_event/SharedEventServiceTest.java
  backend/src/test/java/endolphin/backend/global/scheduler/DiscussionStatusSchedulerTest.java
Labels: 🛠️ BE

#199 [FE-Fix] CD 에러 수정
  frontend/package.json
Labels: 🖥️ FE

#192 [FE-Feat] 세그먼트 컨트롤 구현 수정
  frontend/src/components/SegmentControl/Content.tsx
  frontend/src/components/SegmentControl/ControlButton.tsx
  frontend/src/components/SegmentControl/SegmentControl.stories.tsx
  frontend/src/components/SegmentControl/SegmentControlContext.ts
  frontend/src/components/SegmentControl/index.css.ts
  frontend/src/components/SegmentControl/index.tsx
  frontend/src/features/shared-schedule/ui/UnConfirmedSchedules/index.tsx
Labels: 🖥️ FE

#200 [FE-Feat] 일정 수정 모달 CSS 추가
  .github/workflows/fe-cd.yml
  frontend/src/features/my-calendar/ui/CalendarCard/CardBottom.tsx
  frontend/src/features/my-calendar/ui/MyCalendar/index.css.ts
  frontend/src/features/my-calendar/ui/MyCalendar/index.tsx
  frontend/src/features/my-calendar/ui/SchedulePopover/index.css.ts
  frontend/src/features/my-calendar/ui/SchedulePopover/index.tsx
Labels: 🖥️ FE

#201 [BE-Fix] 로그인 버그 수정
  backend/src/main/java/endolphin/backend/global/security/JwtAuthFilter.java
Labels: 🛠️ BE

#202 [BE-Feat] 토큰 발급 시 만료기한 추가 응답
  backend/src/main/java/endolphin/backend/domain/auth/AuthService.java
  backend/src/main/java/endolphin/backend/domain/auth/dto/OAuthResponse.java
  backend/src/main/java/endolphin/backend/global/security/JwtProvider.java
  backend/src/test/java/endolphin/backend/domain/auth/AuthServiceTest.java
  backend/src/test/java/endolphin/backend/global/security/JwtProviderTest.java
  backend/src/test/resources/application.yml
Labels: 🛠️ BE

#204 [BE-Fix] 구글 캘린더 웹훅 구독 콜백 url을 필터에서 제외
  backend/src/main/java/endolphin/backend/global/security/JwtAuthFilter.java
Labels: 🛠️ BE

#203 [BE-Fix] 구글 캘린더 이벤트 받아올 때 타임존 고정
  backend/src/main/java/endolphin/backend/global/config/GoogleCalendarProperties.java
  backend/src/main/java/endolphin/backend/global/google/GoogleCalendarService.java
Labels: 🛠️ BE

#206 [BE-Fix] 후보일정 검색 버그 수정
  backend/src/main/java/endolphin/backend/domain/candidate_event/CandidateEventService.java
Labels: 🛠️ BE

#209 [BE-Fix] 논의 참여자가 아닐 시 에러 반환
  backend/src/main/java/endolphin/backend/domain/candidate_event/CandidateEventService.java
  backend/src/main/java/endolphin/backend/domain/discussion/DiscussionParticipantService.java
  backend/src/main/java/endolphin/backend/domain/discussion/DiscussionService.java
  backend/src/main/java/endolphin/backend/domain/discussion/dto/CreateDiscussionRequest.java
  backend/src/main/java/endolphin/backend/global/error/exception/ErrorCode.java
  backend/src/test/java/endolphin/backend/domain/discussion/DiscussionServiceTest.java
Labels: 🛠️ BE

#190 [FE-Feat] 조율 결과 랭크뷰 마크업 및 논의 일정 생성, 기본정보 조회 API 연결
  frontend/src/components/Icon/component/Calendar.tsx
  frontend/src/components/Icon/index.ts
  frontend/src/components/Icon/svg/calendar.svg
  frontend/src/components/SegmentControl/index.tsx
  frontend/src/components/Tab/TabItemList.tsx
  frontend/src/constants/regex.ts
  frontend/src/envconfig.ts
  frontend/src/features/discussion/api/index.ts
  frontend/src/features/discussion/api/keys.ts
  frontend/src/features/discussion/api/mutations.ts
  frontend/src/features/discussion/api/queries.ts
  frontend/src/features/discussion/model/index.ts
  frontend/src/features/discussion/ui/DiscussionCalendar/CalendarTable.tsx
  frontend/src/features/discussion/ui/DiscussionCard/DiscussionLarge.tsx
  frontend/src/features/discussion/ui/DiscussionCard/DiscussionSmall.tsx
  frontend/src/features/discussion/ui/DiscussionCard/card.css.ts
  frontend/src/features/discussion/ui/DiscussionCard/index.tsx
  frontend/src/features/discussion/ui/DiscussionCreateCard/DiscussionInfo.tsx
  frontend/src/features/discussion/ui/DiscussionCreateCard/index.tsx
  frontend/src/features/discussion/ui/DiscussionForm/FormButton.tsx
  frontend/src/features/discussion/ui/DiscussionForm/MeetingDateDropdowns.tsx
  frontend/src/features/discussion/ui/DiscussionForm/MeetingDeadlineDropdown.tsx
  frontend/src/features/discussion/ui/DiscussionForm/MeetingPassword.tsx
  frontend/src/features/discussion/ui/DiscussionForm/index.tsx
  frontend/src/features/discussion/ui/DiscussionRank/RankContents.tsx
  frontend/src/features/discussion/ui/DiscussionRank/RankTable.tsx
  frontend/src/features/discussion/ui/DiscussionRank/RankTableRow.tsx
  frontend/src/features/discussion/ui/DiscussionRank/index.css.ts
  frontend/src/features/discussion/ui/DiscussionRank/index.tsx
  frontend/src/features/discussion/ui/DiscussionTab/index.css.ts
  frontend/src/features/discussion/ui/DiscussionTab/index.tsx
  frontend/src/features/login/ui/GoogleLoginButton.tsx
  frontend/src/features/login/ui/index.css.ts
  frontend/src/main.tsx
  frontend/src/pages/DiscussionPage/DiscussionCreateFinishPage/index.tsx
  frontend/src/pages/DiscussionPage/index.tsx
  frontend/src/pages/LoginPage/index.css.ts
  frontend/src/pages/LoginPage/index.tsx
  frontend/src/routes/__root.tsx
  frontend/src/routes/_main.tsx
  frontend/src/routes/_main/discussion/create/$id.tsx
  frontend/src/types/api.ts
  frontend/src/utils/date/format.ts
  frontend/src/utils/date/time.ts
Labels: 🖥️ FE

#215 [BE-Feat] 에러 처리 추가, 에러 명세
  backend/.gitignore
  backend/src/main/java/endolphin/backend/domain/auth/dto/LoginRequest.java
  backend/src/main/java/endolphin/backend/domain/discussion/dto/CreateDiscussionRequest.java
  backend/src/main/java/endolphin/backend/domain/discussion/entity/Discussion.java
  backend/src/main/java/endolphin/backend/domain/personal_event/dto/PersonalEventRequest.java
  backend/src/main/java/endolphin/backend/domain/personal_event/entity/PersonalEvent.java
  backend/src/main/java/endolphin/backend/domain/shared_event/dto/SharedEventRequest.java
  backend/src/main/java/endolphin/backend/global/error/GlobalExceptionHandler.java
  backend/src/main/java/endolphin/backend/global/error/exception/ErrorCode.java
Labels: 🛠️ BE

#217 [BE-Feat] 공유 일정 조회 api 구현
  backend/src/main/java/endolphin/backend/domain/discussion/DiscussionController.java
  backend/src/main/java/endolphin/backend/domain/discussion/DiscussionService.java
  backend/src/main/java/endolphin/backend/global/error/exception/ErrorCode.java
  backend/src/main/java/endolphin/backend/global/util/Validator.java
  backend/src/test/java/endolphin/backend/domain/discussion/DiscussionServiceTest.java
  backend/src/test/resources/application.yml
Labels: 🛠️ BE

#210 [BE-Feat] 다가오는 일정 조회 기능 구현
  backend/src/main/java/endolphin/backend/domain/discussion/DiscussionParticipantRepository.java
  backend/src/main/java/endolphin/backend/domain/discussion/DiscussionParticipantService.java
  backend/src/main/java/endolphin/backend/domain/discussion/DiscussionService.java
  backend/src/main/java/endolphin/backend/domain/shared_event/SharedEventController.java
  backend/src/main/java/endolphin/backend/domain/shared_event/SharedEventRepository.java
  backend/src/main/java/endolphin/backend/domain/shared_event/SharedEventService.java
  backend/src/test/java/endolphin/backend/domain/discussion/DiscussionParticipantRepositoryTest.java
  backend/src/test/java/endolphin/backend/domain/discussion/DiscussionParticipantServiceTest.java
  backend/src/test/java/endolphin/backend/domain/shared_event/SharedEventServiceTest.java
Labels: 🛠️ BE

#205 [FE-Feat] 일정 조율 캘린더뷰 & 순위뷰, 논의 참여자 목록 API 연결
  frontend/src/components/Checkbox/Checkbox.stories.tsx
  frontend/src/components/Checkbox/CheckboxLabel.tsx
  frontend/src/components/Checkbox/index.tsx
  frontend/src/components/Group/index.tsx
  frontend/src/components/SegmentControl/index.tsx
  frontend/src/components/Tab/TabContent.tsx
  frontend/src/components/Toggle/Toggle.stories.tsx
  frontend/src/features/discussion/api/index.ts
  frontend/src/features/discussion/api/keys.ts
  frontend/src/features/discussion/api/queries.ts
  frontend/src/features/discussion/model/index.ts
  frontend/src/features/discussion/ui/DiscussionCalendar/CalendarDate.tsx
  frontend/src/features/discussion/ui/DiscussionCalendar/CalendarTable.tsx
  frontend/src/features/discussion/ui/DiscussionMemberCheckbox/index.tsx
  frontend/src/features/discussion/ui/DiscussionRank/RankContents.tsx
  frontend/src/features/discussion/ui/DiscussionRank/index.css.ts
  frontend/src/features/discussion/ui/DiscussionRank/index.tsx
  frontend/src/features/discussion/ui/DiscussionTab/index.css.ts
  frontend/src/features/discussion/ui/DiscussionTab/index.tsx
  frontend/src/features/discussion/ui/DiscussionTitle/DiscussionBadges.tsx
  frontend/src/features/discussion/ui/DiscussionTitle/index.tsx
  frontend/src/hooks/useGroup.ts
  frontend/src/pages/DiscussionPage/index.css.ts
  frontend/src/pages/DiscussionPage/index.tsx
  frontend/src/utils/date/format.ts
Labels: 🖥️ FE

#219 [BE-Refactor] 후보 일정 검색 리팩토링
  backend/src/main/java/endolphin/backend/domain/candidate_event/CandidateEventService.java
  backend/src/main/java/endolphin/backend/domain/discussion/DiscussionParticipantRepository.java
  backend/src/main/java/endolphin/backend/domain/discussion/DiscussionParticipantService.java
  backend/src/main/java/endolphin/backend/domain/user/UserService.java
  backend/src/test/java/endolphin/backend/domain/candidate_event/CandidateEventServiceTest.java
  backend/src/test/java/endolphin/backend/domain/discussion/DiscussionParticipantRepositoryTest.java
  backend/src/test/java/endolphin/backend/domain/discussion/DiscussionParticipantServiceTest.java
Labels: 🛠️ BE

#221 [BE-Feat] 개인 일정을 구글 캘린더에 반영하는 기능 구현
  backend/src/main/java/endolphin/backend/domain/auth/AuthService.java
  backend/src/main/java/endolphin/backend/domain/personal_event/PersonalEventController.java
  backend/src/main/java/endolphin/backend/domain/personal_event/PersonalEventService.java
  backend/src/main/java/endolphin/backend/domain/personal_event/entity/PersonalEvent.java
  backend/src/main/java/endolphin/backend/domain/personal_event/event/DeletePersonalEvent.java
  backend/src/main/java/endolphin/backend/domain/personal_event/event/InsertPersonalEvent.java
  backend/src/main/java/endolphin/backend/domain/personal_event/event/UpdatePersonalEvent.java
  backend/src/main/java/endolphin/backend/domain/personal_event/event/handler/PersonalEventHandler.java
  backend/src/main/java/endolphin/backend/domain/user/UserService.java
  backend/src/main/java/endolphin/backend/domain/user/event/LoginEvent.java
  backend/src/main/java/endolphin/backend/global/config/GoogleCalendarUrl.java
  backend/src/main/java/endolphin/backend/global/google/GoogleCalendarService.java
  backend/src/main/java/endolphin/backend/global/google/dto/GoogleEventDateTime.java
  backend/src/main/java/endolphin/backend/global/google/dto/GoogleEventRequest.java
  backend/src/main/java/endolphin/backend/global/google/event/GoogleEventChanged.java
  backend/src/main/java/endolphin/backend/global/google/event/handler/GoogleEventHandler.java
  backend/src/main/java/endolphin/backend/global/util/IdGenerator.java
  backend/src/test/java/endolphin/backend/domain/personal_event/PersonalEventServiceTest.java
  backend/src/test/java/endolphin/backend/global/google/GoogleCalendarServiceTest.java
Labels: 🛠️ BE

#223 [BE-Feat] 논의 참여시 이미 참여자일 경우 400 리턴
  backend/src/main/java/endolphin/backend/domain/discussion/DiscussionParticipantService.java
  backend/src/main/java/endolphin/backend/domain/discussion/DiscussionService.java
  backend/src/main/java/endolphin/backend/global/error/exception/ErrorCode.java
  backend/src/test/java/endolphin/backend/domain/discussion/DiscussionServiceTest.java
Labels: 🛠️ BE

#222 [FE-Feat] 호스트 여부 체크, 일정 확정하기 버튼, 일정 확정 후 라우팅 및 조회 구현
  frontend/src/features/discussion/api/index.ts
  frontend/src/features/discussion/api/keys.ts
  frontend/src/features/discussion/api/mutations.ts
  frontend/src/features/discussion/api/queries.ts
  frontend/src/features/discussion/model/index.ts
  frontend/src/features/discussion/ui/DiscussionCard/DiscussionSmall.tsx
  frontend/src/features/discussion/ui/DiscussionCard/index.tsx
  frontend/src/features/discussion/ui/DiscussionConfirmButton/index.tsx
  frontend/src/features/discussion/ui/DiscussionConfirmCard/BadgeContainer.tsx
  frontend/src/features/discussion/ui/DiscussionConfirmCard/index.tsx
  frontend/src/pages/DiscussionPage/DiscussionConfirmPage/index.tsx
  frontend/src/routes/_main/discussion/confirm/$id.tsx
  frontend/src/routes/discussion/confirm/index.tsx
Labels: 🖥️ FE

#224 [FE-Feat] 일정이 다음날로 넘어가는 경우 & 하루 종일인 경우 대응, 현재 시간에 맞춰서 스크롤
  frontend/src/features/my-calendar/api/queries.ts
  frontend/src/features/my-calendar/ui/CalendarCard/index.css.ts
  frontend/src/features/my-calendar/ui/CalendarCardList/index.tsx
  frontend/src/features/my-calendar/ui/MyCalendar/CalendarTable.tsx
  frontend/src/features/my-calendar/ui/MyCalendar/CalendarTimeBar.tsx
  frontend/src/features/my-calendar/ui/MyCalendar/index.css.ts
  frontend/src/features/my-calendar/ui/MyCalendar/index.tsx
  frontend/src/features/my-calendar/ui/MyCalendar/useScrollToCurrentTime.ts
  frontend/src/features/my-calendar/ui/SchedulePopover/index.css.ts
  frontend/src/theme/animation.css.ts
  frontend/src/utils/date/date.ts
Labels: 🖥️ FE

#227 [BE-Fix] 개인 일정 수정 시 구글 캘린더에 반영되지 않는 버그 수정
  backend/src/main/java/endolphin/backend/domain/personal_event/PersonalEventService.java
Labels: 🛠️ BE

#226 [FE-Feat] 체크박스 [확인] 버튼 누를 때 데이터 다시 가져오기
  frontend/src/features/discussion/api/keys.ts
  frontend/src/features/discussion/api/queries.ts
  frontend/src/features/discussion/model/discussionConfirm.ts
  frontend/src/features/discussion/model/index.ts
  frontend/src/features/discussion/ui/DiscussionCalendar/CalendarTable.tsx
  frontend/src/features/discussion/ui/DiscussionMemberCheckbox/index.tsx
  frontend/src/features/discussion/ui/DiscussionRank/RankContents.tsx
  frontend/src/features/discussion/ui/DiscussionRank/RankTable.tsx
  frontend/src/features/discussion/ui/DiscussionRank/index.tsx
  frontend/src/hooks/useFormRef.ts
  frontend/src/hooks/useGroup.ts
  frontend/src/pages/DiscussionPage/MemberContext.ts
  frontend/src/pages/DiscussionPage/index.tsx
Labels: 🖥️ FE

#230 [FE-Feat] 구글 캘린더 연동 생성, 수정, 삭제 시 반영
  frontend/src/components/Toggle/index.tsx
  frontend/src/features/my-calendar/api/hooks.ts
  frontend/src/features/my-calendar/api/index.ts
  frontend/src/features/my-calendar/api/mutations.ts
  frontend/src/utils/fetch/index.ts
Labels: 🖥️ FE

#225 [FE-Feat] 일정 초대 페이지 기능 구현
  frontend/src/components/Button/index.css.ts
  frontend/src/features/discussion/api/invitationApi.ts
  frontend/src/features/discussion/api/keys.ts
  frontend/src/features/discussion/api/mutations.ts
  frontend/src/features/discussion/api/queries.ts
  frontend/src/features/discussion/api/queryOptions.ts
  frontend/src/features/discussion/model/invitation.ts
  frontend/src/features/discussion/ui/DiscussionConfirmCard/BadgeContainer.tsx
  frontend/src/features/discussion/ui/DiscussionConfirmCard/index.css.ts
  frontend/src/features/discussion/ui/DiscussionInviteCard/index.css.ts
  frontend/src/features/discussion/ui/DiscussionInviteCard/index.tsx
  frontend/src/pages/DiscussionPage/DiscussionInvitePage/index.tsx
  frontend/src/routes/_main/discussion/invite/$id.tsx
  frontend/src/utils/date/time.ts
  frontend/src/utils/zod/index.ts
Labels: 🖥️ FE

#233 [FE-Fix] 빌드 에러 해결
  frontend/src/features/discussion/api/mutations.ts
  frontend/src/features/discussion/api/queries.ts
  frontend/src/features/discussion/ui/DiscussionConfirmCard/BadgeContainer.tsx
  frontend/src/utils/date/time.ts
Labels: 🖥️ FE

#231 [FE-Feat] 로그인 state 추적하여 헤더에 아바타 혹은 로그인 버튼 표시
  frontend/src/components/Avatar/index.tsx
  frontend/src/features/user/api/index.ts
  frontend/src/features/user/api/keys.ts
  frontend/src/features/user/api/queries.ts
  frontend/src/features/user/model/index.ts
  frontend/src/layout/GlobalNavBar/index.css.ts
  frontend/src/layout/GlobalNavBar/index.tsx
  frontend/src/routes/landing/index.tsx
  frontend/src/routes/login/index.lazy.tsx
  frontend/src/utils/auth/index.ts
Labels: 🖥️ FE

#235 [BE-Feat] 확정된 일정을 참여자들의 논의 비트맵에 반영하는 기능 구현
  backend/src/main/java/endolphin/backend/domain/discussion/DiscussionParticipantRepository.java
  backend/src/main/java/endolphin/backend/domain/discussion/DiscussionParticipantService.java
  backend/src/main/java/endolphin/backend/domain/personal_event/PersonalEventPreprocessor.java
  backend/src/main/java/endolphin/backend/domain/personal_event/PersonalEventService.java
Labels: 🛠️ BE

#237 [BE-Feat] 개인 일정 SSE 알림 구현
  backend/src/main/java/endolphin/backend/domain/discussion/DiscussionService.java
  backend/src/main/java/endolphin/backend/domain/personal_event/PersonalEventController.java
  backend/src/main/java/endolphin/backend/domain/personal_event/PersonalEventService.java
  backend/src/main/java/endolphin/backend/domain/personal_event/event/handler/PersonalEventHandler.java
  backend/src/main/java/endolphin/backend/global/sse/CalendarEventController.java
  backend/src/main/java/endolphin/backend/global/sse/SseEmitters.java
  backend/src/test/java/endolphin/backend/domain/discussion/DiscussionServiceTest.java
  backend/src/test/java/endolphin/backend/domain/personal_event/PersonalEventServiceTest.java
Labels: 🛠️ BE

#229 [FE-Fix] 일정 생성 시 0N시로 생성되지 않는 문제 해결
  frontend/src/features/my-calendar/ui/MyCalendar/CalendarTimeBar.tsx
  frontend/src/utils/date/format.ts
  frontend/src/utils/date/time.ts
Labels: 🖥️ FE

#238 [BE-Hotfix] 디버그용 로그 추가
  backend/src/main/java/endolphin/backend/domain/personal_event/PersonalEventService.java
  backend/src/main/java/endolphin/backend/domain/personal_event/event/handler/PersonalEventHandler.java
Labels: 🛠️ BE

#241 [BE-Hotfix] 디버깅 로그 추가
  backend/src/main/java/endolphin/backend/global/google/GoogleCalendarService.java
Labels: 🛠️ BE

#242 [BE-Hotfix] 디버깅 로그 추가
  backend/src/main/java/endolphin/backend/global/google/GoogleCalendarService.java
Labels: 🛠️ BE

#243 [BE-Fix] 캘린더 연동 버그 수정
  backend/src/main/java/endolphin/backend/global/google/GoogleCalendarService.java
Labels: 🛠️ BE

#245 [BE-Fix] 구글 캘린더 연동 버그 수정
  backend/src/main/java/endolphin/backend/domain/calendar/CalendarRepository.java
  backend/src/main/java/endolphin/backend/domain/calendar/CalendarService.java
  backend/src/main/java/endolphin/backend/domain/personal_event/PersonalEventService.java
  backend/src/main/java/endolphin/backend/global/google/GoogleCalendarService.java
Labels: 🛠️ BE

#248 [BE-Refactor] 후보일정 전처리 과정 리팩토링
  backend/src/main/java/endolphin/backend/domain/candidate_event/CandidateEventService.java
  backend/src/main/java/endolphin/backend/domain/discussion/DiscussionParticipantService.java
  backend/src/main/java/endolphin/backend/domain/discussion/DiscussionService.java
  backend/src/main/java/endolphin/backend/domain/personal_event/PersonalEventPreprocessor.java
  backend/src/main/java/endolphin/backend/global/redis/DiscussionBitmapService.java
  backend/src/main/java/endolphin/backend/global/util/TimeCalculator.java
  backend/src/main/java/endolphin/backend/global/util/TimeUtil.java
  backend/src/test/java/endolphin/backend/domain/personal_event/PersonalEventPreprocessorTest.java
  backend/src/test/java/endolphin/backend/global/redis/DiscussionBitmapServiceTest.java
Labels: 🛠️ BE

#247 [FE-Feat] 파비콘 및 타이틀 적용
  frontend/index.html
  frontend/public/logo.svg
  frontend/public/vite.svg
Labels: 🖥️ FE

#249 [BE-Fix] scheduler 버그 수정
  backend/src/main/java/endolphin/backend/domain/candidate_event/CandidateEventService.java
  backend/src/main/java/endolphin/backend/global/redis/DiscussionBitmapService.java
  backend/src/main/java/endolphin/backend/global/scheduler/DiscussionStatusScheduler.java
  backend/src/main/java/endolphin/backend/global/util/TimeUtil.java
  backend/src/test/java/endolphin/backend/domain/candidate_event/CandidateEventServiceTest.java
Labels: 🛠️ BE

#228 [FE-Feat] 후보 일정 디테일 화면 API 연결
  frontend/src/features/candidate-schedule/api/index.ts
  frontend/src/features/candidate-schedule/api/keys.ts
  frontend/src/features/candidate-schedule/api/queries.ts
  frontend/src/features/candidate-schedule/api/queryOptions.ts
  frontend/src/features/candidate-schedule/model/index.ts
  frontend/src/features/candidate-schedule/ui/Header.tsx
  frontend/src/features/candidate-schedule/ui/TImelineCanvas/TimelineBlocks.tsx
  frontend/src/features/candidate-schedule/ui/TImelineCanvas/index.css.ts
  frontend/src/features/candidate-schedule/ui/TimelineContent/ParticipantList.tsx
  frontend/src/features/candidate-schedule/ui/index.tsx
  frontend/src/features/discussion/model/index.ts
  frontend/src/features/discussion/ui/DiscussionCalendar/CalendarDate.tsx
  frontend/src/features/discussion/ui/DiscussionCalendar/CalendarTable.tsx
  frontend/src/features/discussion/ui/DiscussionCard/card.css.ts
  frontend/src/features/discussion/ui/DiscussionCard/index.tsx
  frontend/src/features/shared-schedule/api/keys.ts
  frontend/src/features/shared-schedule/api/queryOptions.ts
  frontend/src/features/shared-schedule/model/index.ts
  frontend/src/features/shared-schedule/model/upcomingSchedules.ts
  frontend/src/features/shared-schedule/ui/OngoingSchedules/OngoingScheduleList.tsx
  frontend/src/features/shared-schedule/ui/OngoingSchedules/RecommendedSchedules.tsx
  frontend/src/features/shared-schedule/ui/OngoingSchedules/ScheduleDetails.tsx
  frontend/src/features/shared-schedule/ui/OngoingSchedules/index.tsx
  frontend/src/features/shared-schedule/ui/OngoingSchedules/recommendedSchedules.css.ts
  frontend/src/features/shared-schedule/ui/UpcomingSchedules/ScheduleCard.tsx
  frontend/src/features/shared-schedule/ui/UpcomingSchedules/UpcomingCarousel.tsx
  frontend/src/features/shared-schedule/ui/UpcomingSchedules/UpcomingScheduleList.tsx
  frontend/src/features/shared-schedule/ui/UpcomingSchedules/index.css.ts
  frontend/src/features/shared-schedule/ui/UpcomingSchedules/index.tsx
  frontend/src/main.tsx
  frontend/src/pages/CandidateSchedulePage/index.tsx
  frontend/src/pages/DiscussionPage/MemberContext.ts
  frontend/src/pages/HomePage/index.tsx
  frontend/src/pages/UpcomingSchedulePage/index.css.ts
  frontend/src/pages/UpcomingSchedulePage/index.tsx
  frontend/src/routes/_main/discussion/candidate/$id.lazy.tsx
  frontend/src/routes/_main/discussion/candidate/index.lazy.tsx
  frontend/src/utils/date/format.ts
Labels: 🖥️ FE

#246 [FE-Fix] 체크박스 [확인] 버튼 누를 때마다 요청 보내기 & QA사항
  frontend/src/components/Calendar/Core/SelectedWeek.tsx
  frontend/src/components/Calendar/Core/WeekCell.tsx
  frontend/src/components/Chip/index.css.ts
  frontend/src/features/discussion/api/keys.ts
  frontend/src/features/discussion/ui/DiscussionCalendar/CalendarDate.tsx
  frontend/src/features/discussion/ui/DiscussionCalendar/CalendarTable.tsx
  frontend/src/features/discussion/ui/DiscussionCalendar/index.css.ts
  frontend/src/features/discussion/ui/DiscussionMemberCheckbox/index.tsx
  frontend/src/features/discussion/ui/DiscussionTab/index.tsx
  frontend/src/features/my-calendar/ui/CalendarCard/Card.tsx
  frontend/src/features/my-calendar/ui/MyCalendar/CalendarTable.tsx
  frontend/src/theme/animation.css.ts
Labels: 🖥️ FE

#253 [BE-Fix] 후보일정 디테일 버그 수정
  backend/src/main/java/endolphin/backend/domain/discussion/DiscussionService.java
Labels: 🛠️ BE

#254 [BE-Fix] 빈 유저리스트 버그 재수정
  backend/src/main/java/endolphin/backend/domain/discussion/DiscussionService.java
Labels: 🛠️ BE

#255 [BE-Fix] 겹치는 개인 일정 삭제 시 비트맵 반영하지 않도록 수정
  backend/src/main/java/endolphin/backend/domain/personal_event/PersonalEventPreprocessor.java
  backend/src/main/java/endolphin/backend/domain/personal_event/PersonalEventRepository.java
  backend/src/main/java/endolphin/backend/global/google/GoogleCalendarService.java
  backend/src/test/java/endolphin/backend/domain/personal_event/PersonalEventPreprocessorTest.java
  backend/src/test/java/endolphin/backend/global/redis/DiscussionBitmapServiceTest.java
Labels: 🛠️ BE

#250 [FE-Feat] 401 처리, 토큰 만료 기간 처리, 에러핸들링
  frontend/eslint.config.js
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/src/components/Notification/GlobalNotification.tsx
  frontend/src/components/Notification/NotificationProvider.tsx
  frontend/src/components/Notification/index.css.ts
  frontend/src/constants/error.ts
  frontend/src/features/discussion/ui/DiscussionInviteCard/index.tsx
  frontend/src/features/login/api/mutations.ts
  frontend/src/features/login/model/index.ts
  frontend/src/hooks/useClipboard.ts
  frontend/src/main.tsx
  frontend/src/routes/__root.tsx
  frontend/src/store/global/notification.ts
  frontend/src/utils/auth/index.ts
  frontend/src/utils/error/HTTPError.ts
  frontend/src/utils/error/handleError.ts
  frontend/src/utils/error/index.ts
  frontend/src/utils/fetch/index.ts
Labels: 🖥️ FE

#256 [BE-Fix] OUT_OF_RANGE의 기준 변경
  backend/src/main/java/endolphin/backend/domain/personal_event/dto/PersonalEventWithStatus.java
Labels: 🛠️ BE

#258 [FE-Fix] 일정 확정하기 페이지 CSS 수정
  frontend/src/features/discussion/ui/DiscussionConfirmCard/index.css.ts
  frontend/src/features/discussion/ui/DiscussionConfirmCard/index.tsx
  frontend/src/pages/DiscussionPage/DiscussionConfirmPage/index.css.ts
  frontend/src/pages/DiscussionPage/DiscussionConfirmPage/index.tsx
Labels: 🖥️ FE

#260 [FE-Fix] 랭크뷰에서의 조정해야 할 유저 수 처리, 노티피케이션 CSS
  frontend/src/components/Notification/index.css.ts
  frontend/src/features/discussion/ui/DiscussionCard/DiscussionLarge.tsx
Labels: 🖥️ FE

#261 [FE-Fix] 초대 모달 CSS 삭제
  frontend/src/features/discussion/ui/DiscussionInviteCard/index.tsx
Labels: 🖥️ FE

#262 [BE-Fix] 후보 일정 검색 중복 항목 버그 수정
  backend/src/main/java/endolphin/backend/domain/candidate_event/CandidateEventService.java
Labels: 🛠️ BE

#263 [BE-Fix] 검색 시작시간이 잘못 설정되어있던 버그 수정
  backend/src/main/java/endolphin/backend/domain/candidate_event/CandidateEventService.java
  backend/src/main/java/endolphin/backend/global/util/TimeUtil.java
Labels: 🛠️ BE

#269 [FE-Feat] 초대장 페이지 OG태그 설정
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/src/pages/DiscussionPage/DiscussionInvitePage/index.tsx
  frontend/src/routes/__root.tsx
  frontend/src/routes/_main/discussion/invite/$id.tsx
Labels: 🖥️ FE

#270 [FE-Fix] OG태그 속성명 변경
  frontend/src/routes/_main/discussion/invite/$id.tsx
Labels: 🖥️ FE

#264 [BE-Fix] 스케줄러 실행 시간 기준을 KST로 수정
  backend/src/main/java/endolphin/backend/global/scheduler/DiscussionStatusScheduler.java
Labels: 🛠️ BE

#265 [BE-Fix] 비트맵 삭제되지 않는 버그 수정
  backend/src/main/java/endolphin/backend/domain/personal_event/PersonalEventRepository.java
Labels: 🛠️ BE

#274 [BE-Feat] ONGOING 논의 종료 시 비트맵 데이터 삭제 로직 추가
  backend/src/main/java/endolphin/backend/global/scheduler/DiscussionStatusScheduler.java
  backend/src/test/java/endolphin/backend/global/scheduler/DiscussionStatusSchedulerTest.java
Labels: 🛠️ BE

#271 [BE-Refactor] Time Util 리팩토링
  backend/src/main/java/endolphin/backend/domain/auth/AuthService.java
  backend/src/main/java/endolphin/backend/domain/candidate_event/CandidateEventService.java
  backend/src/main/java/endolphin/backend/domain/personal_event/PersonalEventPreprocessor.java
  backend/src/main/java/endolphin/backend/global/scheduler/DiscussionStatusScheduler.java
  backend/src/main/java/endolphin/backend/global/security/JwtProvider.java
  backend/src/main/java/endolphin/backend/global/util/TimeUtil.java
  backend/src/test/java/endolphin/backend/global/security/JwtAuthFilterTest.java
Labels: 🛠️ BE

#273 [BE-Feat] 사용자 이름 변경 기능 구현
  backend/src/main/java/endolphin/backend/domain/user/UserController.java
  backend/src/main/java/endolphin/backend/domain/user/UserService.java
  backend/src/main/java/endolphin/backend/domain/user/dto/UsernameRequest.java
  backend/src/main/java/endolphin/backend/domain/user/entity/User.java
Labels: 🛠️ BE

#277 [BE-Fix] 후보일정 검색 버그 수정
  backend/src/main/java/endolphin/backend/domain/candidate_event/CandidateEventService.java
  backend/src/main/java/endolphin/backend/global/redis/DiscussionBitmapService.java
  backend/src/main/java/endolphin/backend/global/util/TimeUtil.java
  backend/src/test/java/endolphin/backend/global/redis/DiscussionBitmapServiceTest.java
Labels: 🛠️ BE

#275 [BE-Fix] 웹훅 구독 갱신 버그 수정
  backend/src/main/java/endolphin/backend/global/google/GoogleCalendarService.java
Labels: 🛠️ BE

#267 [FE-Fix] 폼 관련 QA 사항 반영 & 폼 리팩터링
  frontend/src/features/discussion/ui/DiscussionForm/FormButton.tsx
  frontend/src/features/discussion/ui/DiscussionForm/FormProvider.tsx
  frontend/src/features/discussion/ui/DiscussionForm/MeetingDateDropdowns.tsx
  frontend/src/features/discussion/ui/DiscussionForm/MeetingDeadlineDropdown.tsx
  frontend/src/features/discussion/ui/DiscussionForm/MeetingDurationDropdown.tsx
  frontend/src/features/discussion/ui/DiscussionForm/MeetingMethodDropdown.tsx
  frontend/src/features/discussion/ui/DiscussionForm/MeetingPassword.tsx
  frontend/src/features/discussion/ui/DiscussionForm/MeetingTimeDropdowns.tsx
  frontend/src/features/discussion/ui/DiscussionForm/MeetingTitle.tsx
  frontend/src/features/discussion/ui/DiscussionForm/index.tsx
  frontend/src/hooks/useFormState.ts
  frontend/src/utils/date/format.ts
Labels: 🖥️ FE

#282 [BE-Fix] Validation 관련 에러 처리 수정
  backend/src/main/java/endolphin/backend/domain/discussion/dto/CreateDiscussionRequest.java
  backend/src/main/java/endolphin/backend/domain/personal_event/dto/PersonalEventRequest.java
  backend/src/main/java/endolphin/backend/global/error/GlobalExceptionHandler.java
Labels: 🛠️ BE

#283 [BE-Feat] 데이터베이스 Index 추가
  backend/src/main/java/endolphin/backend/domain/candidate_event/CandidateEventService.java
  backend/src/main/java/endolphin/backend/domain/discussion/entity/Discussion.java
  backend/src/main/java/endolphin/backend/domain/discussion/entity/DiscussionParticipant.java
  backend/src/main/java/endolphin/backend/domain/personal_event/entity/PersonalEvent.java
  backend/src/main/java/endolphin/backend/domain/shared_event/entity/SharedEvent.java
Labels: 🛠️ BE

#279 [FE-Fix] 홈 화면 관련 버그 수정 및 UX 개선 반영
  frontend/src/components/Pagination/index.tsx
  frontend/src/features/discussion/ui/DiscussionConfirmCard/index.tsx
  frontend/src/features/shared-schedule/model/finishedSchedules.ts
  frontend/src/features/shared-schedule/ui/FinishedSchedules/FinishedScheduleList.tsx
  frontend/src/features/shared-schedule/ui/FinishedSchedules/FinishedScheduleListItem.tsx
  frontend/src/features/shared-schedule/ui/FinishedSchedules/finishedScheduleListItem.css.ts
  frontend/src/features/shared-schedule/ui/OngoingSchedules/OngoingScheduleList.tsx
  frontend/src/features/shared-schedule/ui/OngoingSchedules/RecommendedSchedules.tsx
  frontend/src/features/shared-schedule/ui/OngoingSchedules/recommendedSchedules.css.ts
  frontend/src/features/shared-schedule/ui/UpcomingSchedules/ScheduleCard.tsx
  frontend/src/features/shared-schedule/ui/UpcomingSchedules/UpcomingScheduleListItem.tsx
  frontend/src/features/timeline-schedule/ui/TimelineContent/ChipAble.tsx
  frontend/src/features/timeline-schedule/ui/TimelineContent/ParticipantList.tsx
  frontend/src/features/timeline-schedule/ui/TimelineContent/chipAble.css.ts
  frontend/src/features/timeline-schedule/ui/TimelineContent/participantList.css.ts
  frontend/src/features/timeline-schedule/ui/TimelineContext.ts
  frontend/src/features/timeline-schedule/ui/index.css.ts
  frontend/src/features/timeline-schedule/ui/index.tsx
  frontend/src/main.tsx
  frontend/src/pages/UpcomingScheduleDetailPage/index.tsx
  frontend/src/utils/date/date.ts
  frontend/src/utils/date/format.ts
  frontend/src/utils/date/time.ts
Labels: 🖥️ FE

#287 [BE-Feat] Ongoing discussion 정보에 time range, duration 추가
  backend/src/main/java/endolphin/backend/domain/discussion/DiscussionParticipantService.java
  backend/src/main/java/endolphin/backend/domain/discussion/dto/OngoingDiscussion.java
Labels: 🛠️ BE

#288 [BE-Feat] CD 파일 수정
  .github/workflows/be-cd.yml
Labels: 🛠️ BE

#289 [BE-Refactor] 코드 줄바꿈, 사용하지 않는 import문 삭제
  backend/src/main/java/endolphin/backend/BackendApplication.java
  backend/src/main/java/endolphin/backend/domain/auth/AuthService.java
  backend/src/main/java/endolphin/backend/domain/calendar/entity/Calendar.java
  backend/src/main/java/endolphin/backend/domain/candidate_event/dto/CandidateEvent.java
  backend/src/main/java/endolphin/backend/domain/discussion/DiscussionController.java
  backend/src/main/java/endolphin/backend/domain/discussion/DiscussionParticipantService.java
  backend/src/main/java/endolphin/backend/domain/discussion/dto/CreateDiscussionRequest.java
  backend/src/main/java/endolphin/backend/domain/personal_event/PersonalEventService.java
  backend/src/main/java/endolphin/backend/domain/personal_event/dto/PersonalEventRequest.java
  backend/src/main/java/endolphin/backend/domain/personal_event/dto/PersonalEventResponse.java
  backend/src/main/java/endolphin/backend/domain/personal_event/dto/PersonalEventWithStatus.java
  backend/src/main/java/endolphin/backend/domain/personal_event/enums/PersonalEventStatus.java
  backend/src/main/java/endolphin/backend/domain/personal_event/event/handler/PersonalEventHandler.java
  backend/src/main/java/endolphin/backend/domain/shared_event/SharedEventController.java
  backend/src/main/java/endolphin/backend/domain/shared_event/SharedEventService.java
  backend/src/main/java/endolphin/backend/domain/shared_event/dto/SharedEventDto.java
  backend/src/main/java/endolphin/backend/domain/user/UserService.java
  backend/src/main/java/endolphin/backend/domain/user/dto/CurrentUserInfo.java
  backend/src/main/java/endolphin/backend/global/error/ErrorResponse.java
  backend/src/main/java/endolphin/backend/global/error/exception/ApiException.java
  backend/src/main/java/endolphin/backend/global/error/exception/CalendarException.java
  backend/src/main/java/endolphin/backend/global/error/exception/ErrorCode.java
  backend/src/main/java/endolphin/backend/global/google/GoogleCalendarService.java
  backend/src/main/java/endolphin/backend/global/google/GoogleController.java
  backend/src/main/java/endolphin/backend/global/google/dto/EventTime.java
  backend/src/main/java/endolphin/backend/global/google/dto/GoogleEventDateTime.java
  backend/src/main/java/endolphin/backend/global/google/dto/GoogleEventRequest.java
  backend/src/main/java/endolphin/backend/global/google/enums/GoogleEventStatus.java
  backend/src/main/java/endolphin/backend/global/google/event/handler/GoogleEventHandler.java
  backend/src/main/java/endolphin/backend/global/logging/LogFilter.java
  backend/src/main/java/endolphin/backend/global/security/UserInfo.java
  backend/src/main/java/endolphin/backend/global/sse/SseEmitters.java
  backend/src/main/java/endolphin/backend/global/util/IdGenerator.java
  backend/src/main/java/endolphin/backend/global/util/RetryExecutor.java
  backend/src/main/java/endolphin/backend/global/util/Validator.java
Labels: 🛠️ BE

#285 [FE-Feat] 헤더 아바타 드롭다운 구현 (로그아웃, 닉네임 수정)
  frontend/src/components/Avatar/AvatarItem.tsx
  frontend/src/components/Avatar/index.tsx
  frontend/src/components/Dropdown/Dropdown.stories.tsx
  frontend/src/components/Dropdown/DropdownContents.tsx
  frontend/src/components/Dropdown/DropdownContext.ts
  frontend/src/components/Dropdown/DropdownItem.tsx
  frontend/src/components/Dropdown/index.tsx
  frontend/src/components/Input/MultiInput.tsx
  frontend/src/components/Input/SingleInput.tsx
  frontend/src/components/Input/index.tsx
  frontend/src/components/Modal/GlobalModal.tsx
  frontend/src/components/Modal/Modal.stories.tsx
  frontend/src/components/Modal/ModalContext.ts
  frontend/src/components/Modal/ModalProvider.tsx
  frontend/src/components/Modal/index.tsx
  frontend/src/features/discussion/ui/DiscussionConfirmCard/WarnModal.tsx
  frontend/src/features/discussion/ui/DiscussionForm/MeetingDurationDropdown.tsx
  frontend/src/features/discussion/ui/DiscussionForm/MeetingMethodDropdown.tsx
  frontend/src/features/discussion/ui/DiscussionForm/MeetingTimeDropdowns.tsx
  frontend/src/features/user/api/index.ts
  frontend/src/features/user/api/mutations.ts
  frontend/src/features/user/model/index.ts
  frontend/src/hooks/useClickOutside.ts
  frontend/src/hooks/useModal.ts
  frontend/src/layout/GlobalNavBar/UserAvatar.tsx
  frontend/src/layout/GlobalNavBar/index.css.ts
  frontend/src/layout/GlobalNavBar/index.tsx
  frontend/src/routes/__root.tsx
  frontend/src/store/global/modal.ts
  frontend/src/utils/auth/index.ts
  frontend/src/utils/fetch/index.ts
Labels: 🖥️ FE

#286 [FE-Feat] 내 일정 페이지 조율 중인 일정 카드 추가
  frontend/src/features/my-calendar/ui/MyCalendar/CalendarDiscussionBox.tsx
  frontend/src/features/my-calendar/ui/MyCalendar/CalendarTable.tsx
  frontend/src/features/my-calendar/ui/MyCalendar/index.css.ts
  frontend/src/features/my-calendar/ui/OngoingDiscussion/OngoingCardItem.tsx
  frontend/src/features/my-calendar/ui/OngoingDiscussion/OngoingCardList.tsx
  frontend/src/features/my-calendar/ui/OngoingDiscussion/index.css.ts
  frontend/src/features/my-calendar/ui/OngoingDiscussion/index.tsx
  frontend/src/features/my-calendar/ui/ProgressDiscussion/index.css.ts
  frontend/src/features/my-calendar/ui/SideBar/index.css.ts
  frontend/src/features/my-calendar/ui/SideBar/index.tsx
  frontend/src/features/shared-schedule/model/ongoingSchedules.ts
  frontend/src/hooks/useSelectDateRange.ts
  frontend/src/pages/MyCalendarPage/DiscussionContext.ts
  frontend/src/pages/MyCalendarPage/index.tsx
  frontend/src/theme/animation.css.ts
  frontend/src/utils/date/date.ts
Labels: 🖥️ FE

#294 [All-Chore] Readme 주요 기능 추가 및 역할 추가
  README.md
Labels: 🔮 ALL

#300 [BE-Feat] 논의 참여 인증 실패 시 처리 수정
  backend/src/main/java/endolphin/backend/domain/discussion/DiscussionService.java
  backend/src/main/java/endolphin/backend/domain/discussion/dto/InvitationInfo.java
  backend/src/main/java/endolphin/backend/global/error/exception/ErrorCode.java
  backend/src/main/java/endolphin/backend/global/redis/PasswordCountService.java
  backend/src/main/java/endolphin/backend/global/security/JwtAuthFilter.java
  backend/src/test/java/endolphin/backend/domain/discussion/DiscussionServiceTest.java
  backend/src/test/java/endolphin/backend/global/redis/PasswordCountServiceTest.java
Labels: 🛠️ BE

#303 [BE-Fix] 구글에서 반영된 일정이 항상 조정 불가능으로 되는 버그 수정
  backend/src/main/java/endolphin/backend/domain/personal_event/PersonalEventService.java
  backend/src/main/java/endolphin/backend/domain/personal_event/dto/PersonalEventRequest.java
Labels: 🛠️ BE

#301 [FE-Feat] 진행 중인 조율로 이동 및 QA사항 해결
  frontend/src/features/my-calendar/ui/CalendarCardList/index.tsx
  frontend/src/features/my-calendar/ui/MyCalendar/CalendarDiscussionBox.tsx
  frontend/src/features/my-calendar/ui/MyCalendar/CalendarTable.tsx
  frontend/src/features/my-calendar/ui/MyCalendar/index.css.ts
  frontend/src/features/my-calendar/ui/MyCalendar/index.tsx
  frontend/src/features/my-calendar/ui/MyCalendar/useScrollToCurrentTime.ts
  frontend/src/features/my-calendar/ui/OngoingDiscussion/OngoingCardList.tsx
  frontend/src/hooks/useScrollToTime.ts
  frontend/src/hooks/useSelectTime.ts
  frontend/src/pages/HomePage/index.tsx
  frontend/src/pages/MyCalendarPage/TableContext.ts
  frontend/src/pages/MyCalendarPage/index.tsx
  frontend/src/utils/date/date.ts
  frontend/src/utils/date/position.ts
  frontend/src/utils/error/HTTPError.ts
  frontend/src/utils/error/handleError.ts
Labels: 🖥️ FE

#310 [BE-Fix] 토큰 재할당 뒤 적용이 되지 않던 버그 수정
  backend/src/main/java/endolphin/backend/global/google/GoogleCalendarService.java
Labels: 🛠️ BE

#304 [FE-Fix] 일정 조율 결과 순위 뷰에서 list item에 Link 연결, 헤더의 cursor:pointer 제거, 로고에 padding 추가
  frontend/src/features/discussion/ui/DiscussionCard/card.css.ts
  frontend/src/features/discussion/ui/DiscussionCard/index.tsx
  frontend/src/features/discussion/ui/DiscussionRank/RankTableRow.tsx
  frontend/src/features/discussion/ui/DiscussionRank/index.css.ts
  frontend/src/hooks/useNavigateToCandidate.ts
  frontend/src/layout/GlobalNavBar/index.css.ts
  frontend/src/layout/GlobalNavBar/index.tsx
Labels: 🖥️ FE

#311 [BE-Chore] 로그파일 수정
  backend/src/main/java/endolphin/backend/domain/candidate_event/CandidateEventService.java
  backend/src/main/resources/logback-spring.xml
Labels: 🛠️ BE
